// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "github.com/luyb177/XiaoAnBackend/xiaoan/internal/handler/auth"
	content "github.com/luyb177/XiaoAnBackend/xiaoan/internal/handler/content"
	qa "github.com/luyb177/XiaoAnBackend/xiaoan/internal/handler/qa"
	"github.com/luyb177/XiaoAnBackend/xiaoan/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 登录
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// 注册
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// 发送邮箱验证码
					Method:  http.MethodPost,
					Path:    "/send-email",
					Handler: auth.SendEmailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 切换班级
					Method:  http.MethodPost,
					Path:    "/change-class",
					Handler: auth.ChangeClassHandler(serverCtx),
				},
				{
					// 生成班级
					Method:  http.MethodPost,
					Path:    "/generate-class",
					Handler: auth.GenerateClassHandler(serverCtx),
				},
				{
					// 生成邀请码
					Method:  http.MethodPost,
					Path:    "/generate-invite-code",
					Handler: auth.GenerateInviteCodeHandler(serverCtx),
				},
				{
					// 获取班级信息
					Method:  http.MethodGet,
					Path:    "/get-class-info",
					Handler: auth.GetClassInfoHandler(serverCtx),
				},
				{
					// 获取班级列表
					Method:  http.MethodGet,
					Path:    "/get-classes",
					Handler: auth.GetClassesHandler(serverCtx),
				},
				{
					// 获取邀请码
					Method:  http.MethodGet,
					Path:    "/get-invite-code",
					Handler: auth.GetInviteCodeHandler(serverCtx),
				},
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/get-user-info",
					Handler: auth.GetUserInfoHandler(serverCtx),
				},
				{
					// 失效邀请码
					Method:  http.MethodPost,
					Path:    "/invalidate-invite-code",
					Handler: auth.InvalidateInviteCodeHandler(serverCtx),
				},
				{
					// 修改用户基本信息
					Method:  http.MethodPost,
					Path:    "/modify-user-base-info",
					Handler: auth.ModifyUserBaseInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 添加文章
					Method:  http.MethodPost,
					Path:    "/add-article",
					Handler: content.AddArticleHandler(serverCtx),
				},
				{
					// 添加漫画
					Method:  http.MethodPost,
					Path:    "/add-comic",
					Handler: content.AddComicHandler(serverCtx),
				},
				{
					// 添加漫画章节
					Method:  http.MethodPost,
					Path:    "/add-comic-chapter",
					Handler: content.AddComicChapterHandler(serverCtx),
				},
				{
					// 添加评论
					Method:  http.MethodPost,
					Path:    "/add-comment",
					Handler: content.AddCommentHandler(serverCtx),
				},
				{
					// 添加播客
					Method:  http.MethodPost,
					Path:    "/add-podcast",
					Handler: content.AddPodcastHandler(serverCtx),
				},
				{
					// 添加视频
					Method:  http.MethodPost,
					Path:    "/add-video",
					Handler: content.AddVideoHandler(serverCtx),
				},
				{
					// 收藏
					Method:  http.MethodPost,
					Path:    "/collect",
					Handler: content.CollectHandler(serverCtx),
				},
				{
					// 删除文章
					Method:  http.MethodDelete,
					Path:    "/delete-article",
					Handler: content.DeleteArticleHandler(serverCtx),
				},
				{
					// 删除漫画
					Method:  http.MethodDelete,
					Path:    "/delete-comic",
					Handler: content.DeleteComicHandler(serverCtx),
				},
				{
					// 删除漫画章节
					Method:  http.MethodDelete,
					Path:    "/delete-comic-chapter",
					Handler: content.DeleteComicChapterHandler(serverCtx),
				},
				{
					// 删除评论
					Method:  http.MethodDelete,
					Path:    "/delete-comment",
					Handler: content.DeleteCommentHandler(serverCtx),
				},
				{
					// 删除播客
					Method:  http.MethodDelete,
					Path:    "/delete-podcast",
					Handler: content.DeletePodcastHandler(serverCtx),
				},
				{
					// 删除视频
					Method:  http.MethodDelete,
					Path:    "/delete-video",
					Handler: content.DeleteVideoHandler(serverCtx),
				},
				{
					// 获取文章详细内容
					Method:  http.MethodGet,
					Path:    "/get-article-content",
					Handler: content.GetArticleContentHandler(serverCtx),
				},
				{
					// 获取漫画
					Method:  http.MethodGet,
					Path:    "/get-comic",
					Handler: content.GetComicHandler(serverCtx),
				},
				{
					// 获取漫画章节
					Method:  http.MethodGet,
					Path:    "/get-comic-chapter",
					Handler: content.GetComicChapterHandler(serverCtx),
				},
				{
					// 获取漫画页面
					Method:  http.MethodGet,
					Path:    "/get-comic-page",
					Handler: content.GetComicPageHandler(serverCtx),
				},
				{
					// 获取最新文章
					Method:  http.MethodGet,
					Path:    "/get-new-articles",
					Handler: content.GetNewArticlesHandler(serverCtx),
				},
				{
					// 获取最新漫画
					Method:  http.MethodGet,
					Path:    "/get-new-comics",
					Handler: content.GetNewComicsHandler(serverCtx),
				},
				{
					// 获取最新播客
					Method:  http.MethodGet,
					Path:    "/get-new-podcasts",
					Handler: content.GetNewPodcastsHandler(serverCtx),
				},
				{
					// 获取最新视频
					Method:  http.MethodGet,
					Path:    "/get-new-videos",
					Handler: content.GetNewVideosHandler(serverCtx),
				},
				{
					// 获取播客详细内容
					Method:  http.MethodGet,
					Path:    "/get-podcast-content",
					Handler: content.GetPodcastContentHandler(serverCtx),
				},
				{
					// 获取根评论
					Method:  http.MethodGet,
					Path:    "/get-root-comment",
					Handler: content.GetRootCommentHandler(serverCtx),
				},
				{
					// 获取子评论
					Method:  http.MethodGet,
					Path:    "/get-sub-comment",
					Handler: content.GetSubCommentHandler(serverCtx),
				},
				{
					// 获取视频详细内容
					Method:  http.MethodGet,
					Path:    "/get-video-content",
					Handler: content.GetVideoContentHandler(serverCtx),
				},
				{
					// 点赞
					Method:  http.MethodPost,
					Path:    "/like",
					Handler: content.LikeHandler(serverCtx),
				},
				{
					// 修改文章
					Method:  http.MethodPost,
					Path:    "/modify-article",
					Handler: content.ModifyArticleHandler(serverCtx),
				},
				{
					// 修改漫画
					Method:  http.MethodPost,
					Path:    "/modify-comic",
					Handler: content.ModifyComicHandler(serverCtx),
				},
				{
					// 修改漫画章节
					Method:  http.MethodPost,
					Path:    "/modify-comic-chapter",
					Handler: content.ModifyComicChapterHandler(serverCtx),
				},
				{
					// 修改播客
					Method:  http.MethodPost,
					Path:    "/modify-podcast",
					Handler: content.ModifyPodcastHandler(serverCtx),
				},
				{
					// 修改视频
					Method:  http.MethodPost,
					Path:    "/modify-video",
					Handler: content.ModifyVideoHandler(serverCtx),
				},
				{
					// 取消收藏
					Method:  http.MethodPost,
					Path:    "/uncollect",
					Handler: content.UnCollectHandler(serverCtx),
				},
				{
					// 取消点赞
					Method:  http.MethodPost,
					Path:    "/unlike",
					Handler: content.UnlikeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/content"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 获取答案
					Method:  http.MethodPost,
					Path:    "/answer",
					Handler: qa.GetAnswerHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/qa"),
	)
}
