// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"
	"time"

	auth "github.com/luyb177/XiaoAnBackend/xiaoan/internal/handler/auth"
	content "github.com/luyb177/XiaoAnBackend/xiaoan/internal/handler/content"
	qa "github.com/luyb177/XiaoAnBackend/xiaoan/internal/handler/qa"
	"github.com/luyb177/XiaoAnBackend/xiaoan/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 发送邮箱验证码
				Method:  http.MethodPost,
				Path:    "/send-email",
				Handler: auth.SendEmailHandler(serverCtx),
			},
			{
				// 验证邮箱验证码
				Method:  http.MethodPost,
				Path:    "/validate-email",
				Handler: auth.ValidateEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 上传文件（流式传输到gRPC）
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: content.UploadContentStreamHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/content"),
		rest.WithTimeout(60000*time.Millisecond),
		rest.WithMaxBytes(104857600),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取答案
				Method:  http.MethodPost,
				Path:    "/answer",
				Handler: qa.GetAnswerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/qa"),
	)
}
