// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "github.com/luyb177/XiaoAnBackend/xiaoan/internal/handler/auth"
	"github.com/luyb177/XiaoAnBackend/xiaoan/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/send-email",
				Handler: auth.SendEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)
}
