version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod
  issues-exit-code: 2
  go: "1.25.3"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - unparam
    - wastedassign
    - nilnesserr

  exclusions:
    generated: lax
    paths:
      - ".*third_party.*"
      - ".*\\.pb\\.go"
      - ".*_gen\\.go"
    rules:
      - path: _test\.go
        linters:
          - errcheck

# Formatter 配置（仅用于 --fix）
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/luyb177/XiaoAnBackend)
      # ⚠️ skip-generated 不允许在这里！已移除
  # 如果需要跳过生成文件，用 exclusions.generated（可选）
  exclusions:
    generated: strict  # 或 lax，根据你需求

issues:
  new: true
  new-from-merge-base: main
  fix: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true