syntax = "proto3";
import "third_party/google/protobuf/any.proto";
package content;
option go_package = "./content/v1";

// ---------------------------------------------------------------------------------------------------------------------
// =================
// ===== Model =====
// =================
// ---------------------------------------------------------------------------------------------------------------------

message Video {
  uint64 id = 1;
  string name = 2;
  repeated string tag = 3;
  string url = 4;
  string description = 5;
  string cover = 6;
  string author = 7;
  int64 published_at = 8;
  int64 created_at = 9;
  int64 updated_at = 10;
  uint64 like_count = 11;
  uint64 view_count = 12;
  uint64 collect_count = 13;
}

message Comic {
  uint64 id = 1;
  string name = 2;
  repeated string tag = 3;
  repeated string url = 4;
  string description = 5;
  string cover = 6;
  string author = 7;
  int64 create_time = 8;
  int64 created_at = 9;
  int64 update_time = 10;
  uint64 like_count = 11;
  uint64 view_count = 12;
  uint64 collect_count = 13;
}

message Podcast {
  uint64 id = 1;
  string name = 2;
  repeated string tag = 3;
  string url = 4;
  string description = 5;
  string cover = 6;
  string author = 7;
  int64 published_at = 8;
  int64 created_at = 9;
  int64 updated_at = 10;
  uint64 like_count = 11;
  uint64 view_count = 12;
  uint64 collect_count = 13;
  repeated PodcastHighlight highlights = 14;
  int64 last_modified_by = 15;
  int64 relation_status = 16;
  string channel = 17;
  int64 status = 18; // 0: 已发布, 1: 草稿
}

message PodcastHighlight {
  uint64 second = 1;
  string highlight = 2;
}

message Article {
  uint64 id = 1;
  string name = 2;
  repeated string tag = 3;
  string url = 5; // 可能的视频 url
  string description = 6;
  string cover = 7;
  string content = 8;
  string author = 9;
  int64 published_at = 10;
  int64 created_at = 11;
  int64 updated_at = 12;
  uint64 like_count = 13;
  uint64 view_count = 14;
  uint64 collect_count = 15;
  int64 last_modified_by = 16;
  int64 relation_status = 17;
}
// ContentLike 点赞记录
message ContentLike {
  uint64 id = 1;
  string type = 2;  // video,comic,podcast,article,comment
  uint64 target_id = 3;
  uint64 user_id = 4;
  string status = 5; // valid invalid - 有效 无效
  int64 created_at = 6;
  int64 updated_at = 7;
}

// ContentCollect 收藏记录
message ContentCollect {
  uint64 id = 1;
  string type = 2;
  uint64 target_id = 3;
  uint64 user_id = 4;
  string status = 5;
  int64 created_at = 6;
  int64 updated_at = 7;
}

// Comment 评论
message Comment {
  uint64 id = 1;
  string type = 2;
  uint64 target_id = 3;
  uint64 user_id = 4;
  uint64 parent_id = 5; // 为0 则为根评论
  uint64 reply_comment_id = 6;
  uint64 reply_user_id = 7;
  string content = 8;
  uint64 like_count = 9;
  int64 created_at = 10;
  int64 updated_at = 11;
}

// 评论详情
message CommentDetail {
  uint64 id = 1;
  string type = 2;
  uint64 target_id = 3;
  uint64 user_id = 4;
  uint64 parent_id = 5; // 为0 则为根评论
  uint64 reply_comment_id = 6;
  uint64 reply_user_id = 7;
  string content = 8;
  uint64 like_count = 9;
  int64 created_at = 10;
  int64 updated_at = 11;
  bool is_liked = 12; // 用户是否点赞
}

// 评论列表项
message CommentItem {
  CommentDetail comment = 1;  // 评论本身
  repeated CommentDetail child_preview = 2;  // 子评论预览 （默认为前3条）
  int64 child_total = 3;
}

// ---------------------------------------------------------------------------------------------------------------------
// =================
// ==== Request ====
// =================
// ---------------------------------------------------------------------------------------------------------------------

// AddVideoRequest 添加视频请求
message AddVideoRequest {
  string name = 1;
  repeated string tag = 2;
  string url = 3;
  string description = 4;
  string cover = 5;
  string author = 6;
  int64 published_at = 7;
}

// GetVideoRequest 获取视频详细内容请求
message GetVideoRequest {
  uint64 id = 1;
}

// ModifyVideoRequest 修改视频请求
message ModifyVideoRequest {
  uint64 id = 1;
  string name = 2;
  repeated string tag = 3;
  string url = 4;
  string description = 5;
  string cover = 6;
  string author = 7;
  int64 published_at = 8;
}

// DeleteVideoRequest 删除视频请求
message DeleteVideoRequest {
  uint64 id = 1;
}

// AddArticleRequest 添加文章请求
message AddArticleRequest {
  string name = 1;                    // 文章标题
  string description = 2;             // 文章摘要
  string content = 3;                 // 文章正文
  string cover = 4;                   // 封面图
  string url = 5;                     // 视频URL（可选）
  int64 published_at = 6;              // 发表时间（可选）

  repeated string tags = 7;            // 标签

  string author = 9;
}

// GetArticleRequest 获取文章详细内容请求
message GetArticleRequest {
  uint64 id = 1;
}

// DeleteArticleRequest 删除文章请求
message DeleteArticleRequest {
  uint64 id = 1;
}

// ModifyArticleRequest 修改文章请求
message ModifyArticleRequest {
  uint64 id = 1;
  string name = 2;
  repeated string tag =  3;
  string url = 5;
  string description = 6;
  string cover = 7;
  string content = 9;
  string author = 10;
  int64 published_at = 11;
}

// AddPodcastRequest 添加播客请求
message AddPodcastRequest {
  string name = 1;
  string url = 2;
  string description = 3;
  string cover = 4;
  string author = 5;
  int64 published_at = 6;
  string channel = 7;
  int64 status = 8; // 0: 已发布, 1: 草稿
  repeated string tags = 9;
  repeated PodcastHighlight highlights = 10;
}

// GetPodcastRequest 获取播客详细内容请求
message GetPodcastRequest {
  uint64 id = 1;
}

// ModifyPodcastRequest 修改播客请求
message ModifyPodcastRequest {
  uint64 id = 1;
  string name = 2;
  string url = 3;
  string description = 4;
  string cover = 5;
  string author = 6;
  int64 published_at = 7;
  string channel = 8;
  int64 status = 9; // 0: 已发布, 1: 草稿
  repeated string tags = 10;
  repeated PodcastHighlight highlights = 11;
}

// DeletePodcastRequest 删除播客请求
message DeletePodcastRequest {
  uint64 id = 1;
}

message SearchRequest {
  string keyword = 1;        // 搜索关键字
  string type = 2;           // video, comic, podcast, article
  repeated string tag = 3;   // 标签筛选
  int64 page = 4;            // 页码
  int64 page_size = 5;       // 每页数量
}

// 点赞请求
message LikeRequest {
  string type = 1; // video,comic,podcast,article,comment
  uint64 target_id = 2; // 目标ID
}

message collectRequest {
  string type = 1;
  uint64 target_id = 2;
}

// 添加评论
message AddCommentRequest {
  string type = 1;
  uint64 target_id = 2;
  uint64 parent_id = 4;
  uint64 reply_comment_id = 5;
  uint64 reply_user_id = 6;
  string content = 7;
}

// 修改评论
message UpdateCommentRequest {
  uint64 id = 1;
  string content = 2;
}

message DeleteCommentRequest {
  uint64 id = 1;
}

message GetCommentsRequest {
  string type = 1;
  uint64 target_id = 2;
  int64 page = 3;
  int64 page_size = 4;
}

// 获取内容请求
message GetContentRequest {
  string type = 1;
  uint64 content_id = 2;
}


// ---------------------------------------------------------------------------------------------------------------------
// ==================
// ==== Response ====
// ==================
// ---------------------------------------------------------------------------------------------------------------------

message AddVideoResponse {
  uint64 id =  1;
  int64 relation_status = 2;
}


message GetVideoResponse {
  Video video = 1;
}

message ModifyVideoResponse {
  uint64 id =  1;
  int64 relation_status = 2;
}

message AddArticleResponse {
  uint64 id =  1;
  int64 relation_status = 2;
}

message GetArticleResponse {
  Article article = 1;
}

message ModifyArticleResponse {
  uint64 id =  1;
  int64 relation_status = 2;
}

message AddPodcastResponse {
  uint64 id = 1;
  int64 relation_status = 2;
}

message GetPodcastResponse {
  Podcast podcast = 1;
}

message ModifyPodcastResponse {
  uint64 id = 1;
  int64 relation_status = 2;
}

message SearchResponse {
  repeated Video videos = 1;
  repeated Comic comics = 2;
  repeated Podcast podcasts = 3;
  repeated Article articles = 4;
}


message GetCommentsResponse {
  repeated CommentItem comments = 1;  // 评论列表
  int64 total = 2;  // 总数
}

message Response {
  int64 code = 1 ;
  string message = 2;
  google.protobuf.Any data = 3;
}


// ------------------------------------------------------------------------------------------------------------------
// ===============
// ==== Route ====
//================
// ---------------------------------------------------------------------------------------------------------------------


service ContentService {
  // AddArticle 添加文章
  rpc AddArticle(AddArticleRequest) returns (Response);

  // GetArticle 获取文章
  rpc GetArticle(GetArticleRequest) returns (Response);

  // ModifyArticle 修改文章
  rpc ModifyArticle(ModifyArticleRequest) returns (Response);

  // DeleteArticle 删除文章
  rpc DeleteArticle(DeleteArticleRequest) returns (Response);

  // AddVideo 添加视频
  rpc AddVideo(AddVideoRequest) returns (Response);

  // GetVideo 获取视频
  rpc GetVideo(GetVideoRequest) returns (Response);

  // ModifyVideo 修改视频
  rpc ModifyVideo(ModifyVideoRequest) returns (Response);

  // DeleteVideo 删除视频
  rpc DeleteVideo(DeleteVideoRequest) returns (Response);

  // AddPodcast 添加播客
  rpc AddPodcast(AddPodcastRequest) returns (Response);

  // GetPodcast 获取播客
  rpc GetPodcast(GetPodcastRequest) returns (Response);

  // ModifyPodcast 修改播客
  rpc ModifyPodcast(ModifyPodcastRequest) returns (Response);

  // DeletePodcast 删除播客
  rpc DeletePodcast(DeletePodcastRequest) returns (Response);

  // 搜索
  rpc Search(SearchRequest) returns (Response);

  // 点赞
  rpc Like(LikeRequest) returns (Response);

  // 收藏
  rpc Collect(collectRequest) returns (Response);

  // 添加评论
  rpc AddComment(AddCommentRequest) returns (Response);

  // 修改评论
  rpc UpdateComment(UpdateCommentRequest) returns (Response);

  // 删除评论
  rpc DeleteComment(DeleteCommentRequest) returns (Response);

  // 获取根评论
  rpc GetComments(GetCommentsRequest) returns (Response);
}
