// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: content.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           []string               `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Author        string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	LikeCount     uint64                 `protobuf:"varint,11,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewCount     uint64                 `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CollectCount  uint64                 `protobuf:"varint,13,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Video) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Video) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Video) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Video) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Video) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Video) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Video) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Video) GetCollectCount() uint64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

type Comic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           []string               `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	Url           []string               `protobuf:"bytes,4,rep,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Author        string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	LikeCount     uint64                 `protobuf:"varint,11,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewCount     uint64                 `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CollectCount  uint64                 `protobuf:"varint,13,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comic) Reset() {
	*x = Comic{}
	mi := &file_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comic) ProtoMessage() {}

func (x *Comic) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comic.ProtoReflect.Descriptor instead.
func (*Comic) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{1}
}

func (x *Comic) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Comic) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Comic) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *Comic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Comic) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Comic) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Comic) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Comic) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comic) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Comic) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comic) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Comic) GetCollectCount() uint64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

type Podcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           []string               `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Author        string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	LikeCount     uint64                 `protobuf:"varint,11,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewCount     uint64                 `protobuf:"varint,12,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CollectCount  uint64                 `protobuf:"varint,13,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Podcast) Reset() {
	*x = Podcast{}
	mi := &file_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Podcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Podcast) ProtoMessage() {}

func (x *Podcast) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Podcast.ProtoReflect.Descriptor instead.
func (*Podcast) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{2}
}

func (x *Podcast) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Podcast) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Podcast) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Podcast) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Podcast) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Podcast) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Podcast) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Podcast) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Podcast) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Podcast) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Podcast) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Podcast) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Podcast) GetCollectCount() uint64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

type Article struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag            []string               `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	Images         []*ArticleImage        `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Url            string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"` // 可能的视频 url
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Cover          string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Content        string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Author         string                 `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	PublishedAt    int64                  `protobuf:"varint,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikeCount      uint64                 `protobuf:"varint,13,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewCount      uint64                 `protobuf:"varint,14,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CollectCount   uint64                 `protobuf:"varint,15,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	LastModifiedBy int64                  `protobuf:"varint,16,opt,name=last_modified_by,json=lastModifiedBy,proto3" json:"last_modified_by,omitempty"`
	RelationStatus int64                  `protobuf:"varint,17,opt,name=relation_status,json=relationStatus,proto3" json:"relation_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{3}
}

func (x *Article) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Article) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Article) GetImages() []*ArticleImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Article) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Article) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *Article) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Article) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Article) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Article) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Article) GetCollectCount() uint64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *Article) GetLastModifiedBy() int64 {
	if x != nil {
		return x.LastModifiedBy
	}
	return 0
}

func (x *Article) GetRelationStatus() int64 {
	if x != nil {
		return x.RelationStatus
	}
	return 0
}

type ArticleImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Sort          int64                  `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty"` // 图片顺序
	Tp            int64                  `protobuf:"varint,3,opt,name=tp,proto3" json:"tp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleImage) Reset() {
	*x = ArticleImage{}
	mi := &file_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleImage) ProtoMessage() {}

func (x *ArticleImage) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleImage.ProtoReflect.Descriptor instead.
func (*ArticleImage) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ArticleImage) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ArticleImage) GetTp() int64 {
	if x != nil {
		return x.Tp
	}
	return 0
}

// 点赞记录
type ContentLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // video,comic,podcast,article,comment
	TargetId      uint64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // valid invalid - 有效 无效
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentLike) Reset() {
	*x = ContentLike{}
	mi := &file_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentLike) ProtoMessage() {}

func (x *ContentLike) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentLike.ProtoReflect.Descriptor instead.
func (*ContentLike) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{5}
}

func (x *ContentLike) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentLike) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentLike) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ContentLike) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContentLike) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentLike) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ContentLike) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 收藏记录
type ContentCollect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TargetId      uint64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentCollect) Reset() {
	*x = ContentCollect{}
	mi := &file_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentCollect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentCollect) ProtoMessage() {}

func (x *ContentCollect) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentCollect.ProtoReflect.Descriptor instead.
func (*ContentCollect) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{6}
}

func (x *ContentCollect) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentCollect) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentCollect) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ContentCollect) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContentCollect) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentCollect) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ContentCollect) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 评论
type Comment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TargetId       uint64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	UserId         uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId       uint64                 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 为0 则为根评论
	ReplyCommentId uint64                 `protobuf:"varint,6,opt,name=reply_comment_id,json=replyCommentId,proto3" json:"reply_comment_id,omitempty"`
	ReplyUserId    uint64                 `protobuf:"varint,7,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`
	Content        string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount      uint64                 `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{7}
}

func (x *Comment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Comment) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Comment) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetReplyCommentId() uint64 {
	if x != nil {
		return x.ReplyCommentId
	}
	return 0
}

func (x *Comment) GetReplyUserId() uint64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 文件分片请求
type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                    // 每个分片的二进制内容
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"` // 是否最后一片
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{8}
}

func (x *UploadChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// 响应
type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{9}
}

func (x *UploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 获取访问链接请求
type GetContentURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectName    string                 `protobuf:"bytes,1,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"` // MinIO对象名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentURLRequest) Reset() {
	*x = GetContentURLRequest{}
	mi := &file_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentURLRequest) ProtoMessage() {}

func (x *GetContentURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentURLRequest.ProtoReflect.Descriptor instead.
func (*GetContentURLRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{10}
}

func (x *GetContentURLRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

// 获取访问链接响应
type GetContentURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // 有效期秒数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentURLResponse) Reset() {
	*x = GetContentURLResponse{}
	mi := &file_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentURLResponse) ProtoMessage() {}

func (x *GetContentURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentURLResponse.ProtoReflect.Descriptor instead.
func (*GetContentURLResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{11}
}

func (x *GetContentURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetContentURLResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 添加视频
type AddVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           []string               `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	CreateTime    int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideoRequest) Reset() {
	*x = AddVideoRequest{}
	mi := &file_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideoRequest) ProtoMessage() {}

func (x *AddVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideoRequest.ProtoReflect.Descriptor instead.
func (*AddVideoRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{12}
}

func (x *AddVideoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddVideoRequest) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *AddVideoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddVideoRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *AddVideoRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AddVideoRequest) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 添加文章
type AddArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                   // 文章标题
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                     // 文章摘要
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                             // 文章正文
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`                                 // 封面图
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                     // 视频URL（可选）
	PublishedAt   int64                  `protobuf:"varint,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // 发表时间（可选）
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                   // 标签
	Images        []*ArticleImage        `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`                               // 正文图片
	Author        string                 `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticleRequest) Reset() {
	*x = AddArticleRequest{}
	mi := &file_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleRequest) ProtoMessage() {}

func (x *AddArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleRequest.ProtoReflect.Descriptor instead.
func (*AddArticleRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{13}
}

func (x *AddArticleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddArticleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddArticleRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *AddArticleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddArticleRequest) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *AddArticleRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddArticleRequest) GetImages() []*ArticleImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *AddArticleRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type AddArticleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RelationStatus int64                  `protobuf:"varint,2,opt,name=relation_status,json=relationStatus,proto3" json:"relation_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddArticleResponse) Reset() {
	*x = AddArticleResponse{}
	mi := &file_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleResponse) ProtoMessage() {}

func (x *AddArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleResponse.ProtoReflect.Descriptor instead.
func (*AddArticleResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{14}
}

func (x *AddArticleResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddArticleResponse) GetRelationStatus() int64 {
	if x != nil {
		return x.RelationStatus
	}
	return 0
}

// 获取文章详细内容
type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{15}
}

func (x *GetArticleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{16}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ModifyArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           []string               `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	Images        []*ArticleImage        `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Content       string                 `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,11,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyArticleRequest) Reset() {
	*x = ModifyArticleRequest{}
	mi := &file_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyArticleRequest) ProtoMessage() {}

func (x *ModifyArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyArticleRequest.ProtoReflect.Descriptor instead.
func (*ModifyArticleRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{17}
}

func (x *ModifyArticleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModifyArticleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModifyArticleRequest) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *ModifyArticleRequest) GetImages() []*ArticleImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ModifyArticleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ModifyArticleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModifyArticleRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ModifyArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ModifyArticleRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ModifyArticleRequest) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

type ModifyArticleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RelationStatus int64                  `protobuf:"varint,2,opt,name=relation_status,json=relationStatus,proto3" json:"relation_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModifyArticleResponse) Reset() {
	*x = ModifyArticleResponse{}
	mi := &file_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyArticleResponse) ProtoMessage() {}

func (x *ModifyArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyArticleResponse.ProtoReflect.Descriptor instead.
func (*ModifyArticleResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{18}
}

func (x *ModifyArticleResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModifyArticleResponse) GetRelationStatus() int64 {
	if x != nil {
		return x.RelationStatus
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    // 搜索关键字
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                          // video, comic, podcast, article
	Tag           []string               `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`                            // 标签筛选
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{19}
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchRequest) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *SearchRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Comics        []*Comic               `protobuf:"bytes,2,rep,name=comics,proto3" json:"comics,omitempty"`
	Podcasts      []*Podcast             `protobuf:"bytes,3,rep,name=podcasts,proto3" json:"podcasts,omitempty"`
	Articles      []*Article             `protobuf:"bytes,4,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{20}
}

func (x *SearchResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *SearchResponse) GetComics() []*Comic {
	if x != nil {
		return x.Comics
	}
	return nil
}

func (x *SearchResponse) GetPodcasts() []*Podcast {
	if x != nil {
		return x.Podcasts
	}
	return nil
}

func (x *SearchResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

// 点赞请求
type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                          // video,comic,podcast,article,comment
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{21}
}

func (x *LikeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LikeRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{22}
}

func (x *CollectRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CollectRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 添加评论
type AddCommentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TargetId       uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ParentId       uint64                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReplyCommentId uint64                 `protobuf:"varint,5,opt,name=reply_comment_id,json=replyCommentId,proto3" json:"reply_comment_id,omitempty"`
	ReplyUserId    uint64                 `protobuf:"varint,6,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{23}
}

func (x *AddCommentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddCommentRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *AddCommentRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AddCommentRequest) GetReplyCommentId() uint64 {
	if x != nil {
		return x.ReplyCommentId
	}
	return 0
}

func (x *AddCommentRequest) GetReplyUserId() uint64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 修改评论
type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateCommentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteCommentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_content_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{26}
}

func (x *GetCommentsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetCommentsRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *GetCommentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 评论详情
type CommentDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TargetId       uint64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	UserId         uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId       uint64                 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 为0 则为根评论
	ReplyCommentId uint64                 `protobuf:"varint,6,opt,name=reply_comment_id,json=replyCommentId,proto3" json:"reply_comment_id,omitempty"`
	ReplyUserId    uint64                 `protobuf:"varint,7,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`
	Content        string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount      uint64                 `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsLiked        bool                   `protobuf:"varint,12,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"` // 用户是否点赞
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommentDetail) Reset() {
	*x = CommentDetail{}
	mi := &file_content_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentDetail) ProtoMessage() {}

func (x *CommentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentDetail.ProtoReflect.Descriptor instead.
func (*CommentDetail) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{27}
}

func (x *CommentDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommentDetail) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CommentDetail) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentDetail) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentDetail) GetReplyCommentId() uint64 {
	if x != nil {
		return x.ReplyCommentId
	}
	return 0
}

func (x *CommentDetail) GetReplyUserId() uint64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *CommentDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentDetail) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommentDetail) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CommentDetail) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

// 评论列表项
type CommentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentDetail         `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`                               // 评论本身
	ChildPreview  []*CommentDetail       `protobuf:"bytes,2,rep,name=child_preview,json=childPreview,proto3" json:"child_preview,omitempty"` // 子评论预览 （默认为前3条）
	ChildTotal    int64                  `protobuf:"varint,3,opt,name=child_total,json=childTotal,proto3" json:"child_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_content_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{28}
}

func (x *CommentItem) GetComment() *CommentDetail {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *CommentItem) GetChildPreview() []*CommentDetail {
	if x != nil {
		return x.ChildPreview
	}
	return nil
}

func (x *CommentItem) GetChildTotal() int64 {
	if x != nil {
		return x.ChildTotal
	}
	return 0
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentItem         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"` // 评论列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`      // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_content_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{29}
}

func (x *GetCommentsResponse) GetComments() []*CommentItem {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取内容请求
type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ContentId     uint64                 `protobuf:"varint,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_content_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{30}
}

func (x *GetContentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetContentRequest) GetContentId() uint64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_content_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{31}
}

func (x *Response) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_content_proto protoreflect.FileDescriptor

const file_content_proto_rawDesc = "" +
	"\n" +
	"\rcontent.proto\x12\acontent\x1a%third_party/google/protobuf/any.proto\"\xe3\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x03(\tR\x03tag\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"like_count\x18\v \x01(\x04R\tlikeCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x04R\tviewCount\x12#\n" +
	"\rcollect_count\x18\r \x01(\x04R\fcollectCount\"\xe3\x02\n" +
	"\x05Comic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x03(\tR\x03tag\x12\x10\n" +
	"\x03url\x18\x04 \x03(\tR\x03url\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"like_count\x18\v \x01(\x04R\tlikeCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x04R\tviewCount\x12#\n" +
	"\rcollect_count\x18\r \x01(\x04R\fcollectCount\"\xe5\x02\n" +
	"\aPodcast\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x03(\tR\x03tag\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"like_count\x18\v \x01(\x04R\tlikeCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\f \x01(\x04R\tviewCount\x12#\n" +
	"\rcollect_count\x18\r \x01(\x04R\fcollectCount\"\x81\x04\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x03(\tR\x03tag\x12-\n" +
	"\x06images\x18\x04 \x03(\v2\x15.content.ArticleImageR\x06images\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06author\x12!\n" +
	"\fpublished_at\x18\n" +
	" \x01(\x03R\vpublishedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\r \x01(\x04R\tlikeCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x0e \x01(\x04R\tviewCount\x12#\n" +
	"\rcollect_count\x18\x0f \x01(\x04R\fcollectCount\x12(\n" +
	"\x10last_modified_by\x18\x10 \x01(\x03R\x0elastModifiedBy\x12'\n" +
	"\x0frelation_status\x18\x11 \x01(\x03R\x0erelationStatus\"D\n" +
	"\fArticleImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\x03R\x04sort\x12\x0e\n" +
	"\x02tp\x18\x03 \x01(\x03R\x02tp\"\xbd\x01\n" +
	"\vContentLike\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x04R\btargetId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xc0\x01\n" +
	"\x0eContentCollect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x04R\btargetId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xc5\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x04R\btargetId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x04R\bparentId\x12(\n" +
	"\x10reply_comment_id\x18\x06 \x01(\x04R\x0ereplyCommentId\x12\"\n" +
	"\rreply_user_id\x18\a \x01(\x04R\vreplyUserId\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x04R\tlikeCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"V\n" +
	"\vUploadChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"\"\n" +
	"\x0eUploadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"7\n" +
	"\x14GetContentURLRequest\x12\x1f\n" +
	"\vobject_name\x18\x01 \x01(\tR\n" +
	"objectName\"H\n" +
	"\x15GetContentURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"\xba\x01\n" +
	"\x0fAddVideoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x03(\tR\x03tag\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\"\x89\x02\n" +
	"\x11AddArticleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\x03R\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12-\n" +
	"\x06images\x18\b \x03(\v2\x15.content.ArticleImageR\x06images\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06author\"M\n" +
	"\x12AddArticleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0frelation_status\x18\x02 \x01(\x03R\x0erelationStatus\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"@\n" +
	"\x12GetArticleResponse\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.content.ArticleR\aarticle\"\x9a\x02\n" +
	"\x14ModifyArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x03(\tR\x03tag\x12-\n" +
	"\x06images\x18\x04 \x03(\v2\x15.content.ArticleImageR\x06images\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12\x18\n" +
	"\acontent\x18\t \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\n" +
	" \x01(\tR\x06author\x12!\n" +
	"\fpublished_at\x18\v \x01(\x03R\vpublishedAt\"P\n" +
	"\x15ModifyArticleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0frelation_status\x18\x02 \x01(\x03R\x0erelationStatus\"\x80\x01\n" +
	"\rSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\x03 \x03(\tR\x03tag\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"\xbc\x01\n" +
	"\x0eSearchResponse\x12&\n" +
	"\x06videos\x18\x01 \x03(\v2\x0e.content.VideoR\x06videos\x12&\n" +
	"\x06comics\x18\x02 \x03(\v2\x0e.content.ComicR\x06comics\x12,\n" +
	"\bpodcasts\x18\x03 \x03(\v2\x10.content.PodcastR\bpodcasts\x12,\n" +
	"\barticles\x18\x04 \x03(\v2\x10.content.ArticleR\barticles\">\n" +
	"\vLikeRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\"A\n" +
	"\x0ecollectRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\"\xc9\x01\n" +
	"\x11AddCommentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x04R\bparentId\x12(\n" +
	"\x10reply_comment_id\x18\x05 \x01(\x04R\x0ereplyCommentId\x12\"\n" +
	"\rreply_user_id\x18\x06 \x01(\x04R\vreplyUserId\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"@\n" +
	"\x14UpdateCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"&\n" +
	"\x14DeleteCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"v\n" +
	"\x12GetCommentsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\xe6\x02\n" +
	"\rCommentDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x04R\btargetId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x04R\bparentId\x12(\n" +
	"\x10reply_comment_id\x18\x06 \x01(\x04R\x0ereplyCommentId\x12\"\n" +
	"\rreply_user_id\x18\a \x01(\x04R\vreplyUserId\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x04R\tlikeCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x19\n" +
	"\bis_liked\x18\f \x01(\bR\aisLiked\"\x9d\x01\n" +
	"\vCommentItem\x120\n" +
	"\acomment\x18\x01 \x01(\v2\x16.content.CommentDetailR\acomment\x12;\n" +
	"\rchild_preview\x18\x02 \x03(\v2\x16.content.CommentDetailR\fchildPreview\x12\x1f\n" +
	"\vchild_total\x18\x03 \x01(\x03R\n" +
	"childTotal\"]\n" +
	"\x13GetCommentsResponse\x120\n" +
	"\bcomments\x18\x01 \x03(\v2\x14.content.CommentItemR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"F\n" +
	"\x11GetContentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x04R\tcontentId\"b\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data2\xaa\x06\n" +
	"\x0eContentService\x12@\n" +
	"\x13UploadContentStream\x12\x14.content.UploadChunk\x1a\x11.content.Response(\x01\x12A\n" +
	"\rGetContentURL\x12\x1d.content.GetContentURLRequest\x1a\x11.content.Response\x12;\n" +
	"\n" +
	"AddArticle\x12\x1a.content.AddArticleRequest\x1a\x11.content.Response\x12;\n" +
	"\n" +
	"GetArticle\x12\x1a.content.GetArticleRequest\x1a\x11.content.Response\x12A\n" +
	"\rModifyArticle\x12\x1d.content.ModifyArticleRequest\x1a\x11.content.Response\x127\n" +
	"\bAddVideo\x12\x18.content.AddVideoRequest\x1a\x11.content.Response\x123\n" +
	"\x06Search\x12\x16.content.SearchRequest\x1a\x11.content.Response\x12/\n" +
	"\x04Like\x12\x14.content.LikeRequest\x1a\x11.content.Response\x125\n" +
	"\aCollect\x12\x17.content.collectRequest\x1a\x11.content.Response\x12;\n" +
	"\n" +
	"AddComment\x12\x1a.content.AddCommentRequest\x1a\x11.content.Response\x12A\n" +
	"\rUpdateComment\x12\x1d.content.UpdateCommentRequest\x1a\x11.content.Response\x12A\n" +
	"\rDeleteComment\x12\x1d.content.DeleteCommentRequest\x1a\x11.content.Response\x12=\n" +
	"\vGetComments\x12\x1b.content.GetCommentsRequest\x1a\x11.content.ResponseB\x0eZ\f./content/v1b\x06proto3"

var (
	file_content_proto_rawDescOnce sync.Once
	file_content_proto_rawDescData []byte
)

func file_content_proto_rawDescGZIP() []byte {
	file_content_proto_rawDescOnce.Do(func() {
		file_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)))
	})
	return file_content_proto_rawDescData
}

var file_content_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_content_proto_goTypes = []any{
	(*Video)(nil),                 // 0: content.Video
	(*Comic)(nil),                 // 1: content.Comic
	(*Podcast)(nil),               // 2: content.Podcast
	(*Article)(nil),               // 3: content.Article
	(*ArticleImage)(nil),          // 4: content.ArticleImage
	(*ContentLike)(nil),           // 5: content.ContentLike
	(*ContentCollect)(nil),        // 6: content.ContentCollect
	(*Comment)(nil),               // 7: content.Comment
	(*UploadChunk)(nil),           // 8: content.UploadChunk
	(*UploadResponse)(nil),        // 9: content.UploadResponse
	(*GetContentURLRequest)(nil),  // 10: content.GetContentURLRequest
	(*GetContentURLResponse)(nil), // 11: content.GetContentURLResponse
	(*AddVideoRequest)(nil),       // 12: content.AddVideoRequest
	(*AddArticleRequest)(nil),     // 13: content.AddArticleRequest
	(*AddArticleResponse)(nil),    // 14: content.AddArticleResponse
	(*GetArticleRequest)(nil),     // 15: content.GetArticleRequest
	(*GetArticleResponse)(nil),    // 16: content.GetArticleResponse
	(*ModifyArticleRequest)(nil),  // 17: content.ModifyArticleRequest
	(*ModifyArticleResponse)(nil), // 18: content.ModifyArticleResponse
	(*SearchRequest)(nil),         // 19: content.SearchRequest
	(*SearchResponse)(nil),        // 20: content.SearchResponse
	(*LikeRequest)(nil),           // 21: content.LikeRequest
	(*CollectRequest)(nil),        // 22: content.collectRequest
	(*AddCommentRequest)(nil),     // 23: content.AddCommentRequest
	(*UpdateCommentRequest)(nil),  // 24: content.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),  // 25: content.DeleteCommentRequest
	(*GetCommentsRequest)(nil),    // 26: content.GetCommentsRequest
	(*CommentDetail)(nil),         // 27: content.CommentDetail
	(*CommentItem)(nil),           // 28: content.CommentItem
	(*GetCommentsResponse)(nil),   // 29: content.GetCommentsResponse
	(*GetContentRequest)(nil),     // 30: content.GetContentRequest
	(*Response)(nil),              // 31: content.Response
	(*anypb.Any)(nil),             // 32: google.protobuf.Any
}
var file_content_proto_depIdxs = []int32{
	4,  // 0: content.Article.images:type_name -> content.ArticleImage
	4,  // 1: content.AddArticleRequest.images:type_name -> content.ArticleImage
	3,  // 2: content.GetArticleResponse.article:type_name -> content.Article
	4,  // 3: content.ModifyArticleRequest.images:type_name -> content.ArticleImage
	0,  // 4: content.SearchResponse.videos:type_name -> content.Video
	1,  // 5: content.SearchResponse.comics:type_name -> content.Comic
	2,  // 6: content.SearchResponse.podcasts:type_name -> content.Podcast
	3,  // 7: content.SearchResponse.articles:type_name -> content.Article
	27, // 8: content.CommentItem.comment:type_name -> content.CommentDetail
	27, // 9: content.CommentItem.child_preview:type_name -> content.CommentDetail
	28, // 10: content.GetCommentsResponse.comments:type_name -> content.CommentItem
	32, // 11: content.Response.data:type_name -> google.protobuf.Any
	8,  // 12: content.ContentService.UploadContentStream:input_type -> content.UploadChunk
	10, // 13: content.ContentService.GetContentURL:input_type -> content.GetContentURLRequest
	13, // 14: content.ContentService.AddArticle:input_type -> content.AddArticleRequest
	15, // 15: content.ContentService.GetArticle:input_type -> content.GetArticleRequest
	17, // 16: content.ContentService.ModifyArticle:input_type -> content.ModifyArticleRequest
	12, // 17: content.ContentService.AddVideo:input_type -> content.AddVideoRequest
	19, // 18: content.ContentService.Search:input_type -> content.SearchRequest
	21, // 19: content.ContentService.Like:input_type -> content.LikeRequest
	22, // 20: content.ContentService.Collect:input_type -> content.collectRequest
	23, // 21: content.ContentService.AddComment:input_type -> content.AddCommentRequest
	24, // 22: content.ContentService.UpdateComment:input_type -> content.UpdateCommentRequest
	25, // 23: content.ContentService.DeleteComment:input_type -> content.DeleteCommentRequest
	26, // 24: content.ContentService.GetComments:input_type -> content.GetCommentsRequest
	31, // 25: content.ContentService.UploadContentStream:output_type -> content.Response
	31, // 26: content.ContentService.GetContentURL:output_type -> content.Response
	31, // 27: content.ContentService.AddArticle:output_type -> content.Response
	31, // 28: content.ContentService.GetArticle:output_type -> content.Response
	31, // 29: content.ContentService.ModifyArticle:output_type -> content.Response
	31, // 30: content.ContentService.AddVideo:output_type -> content.Response
	31, // 31: content.ContentService.Search:output_type -> content.Response
	31, // 32: content.ContentService.Like:output_type -> content.Response
	31, // 33: content.ContentService.Collect:output_type -> content.Response
	31, // 34: content.ContentService.AddComment:output_type -> content.Response
	31, // 35: content.ContentService.UpdateComment:output_type -> content.Response
	31, // 36: content.ContentService.DeleteComment:output_type -> content.Response
	31, // 37: content.ContentService.GetComments:output_type -> content.Response
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_content_proto_init() }
func file_content_proto_init() {
	if File_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_proto_goTypes,
		DependencyIndexes: file_content_proto_depIdxs,
		MessageInfos:      file_content_proto_msgTypes,
	}.Build()
	File_content_proto = out.File
	file_content_proto_goTypes = nil
	file_content_proto_depIdxs = nil
}
