// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddArticleRequest struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Content     string   `json:"content"`
	Cover       string   `json:"cover"`
	Url         string   `json:"url"`
	PublishedAt int64    `json:"published_at"`
	Author      string   `json:"author"`
	Tags        []string `json:"tags"`
}

type AddArticleResponse struct {
	ArticleId      uint64 `json:"article_id"`
	RelationStatus int64  `json:"relation_status"`
}

type AddComicChapterRequest struct {
	ComicId     uint64   `json:"comic_id"`
	ChapterNo   int64    `json:"chapter_no"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Status      int64    `json:"status"`
	PublishedAt int64    `json:"published_at"`
	PageUrls    []string `json:"page_urls"`
}

type AddComicChapterResponse struct {
	ComicChapterId uint64 `json:"comic_chapter_id"`
	RelationStatus int64  `json:"relation_status"`
}

type AddComicRequest struct {
	Name        string   `json:"name"`
	Tags        []string `json:"tags"`
	Description string   `json:"description"`
	Cover       string   `json:"cover"`
	Author      string   `json:"author"`
	PublishedAt int64    `json:"published_at"`
}

type AddComicResponse struct {
	ComicId        uint64 `json:"comic_id"`
	RelationStatus int64  `json:"relation_status"`
}

type AddCommentRequest struct {
	ContentType    string `json:"content_type"`
	ContentId      uint64 `json:"content_id"`
	UserName       string `json:"user_name"`
	Avatar         string `json:"avatar"`
	ParentId       uint64 `json:"parent_id"`
	ReplyCommentId uint64 `json:"reply_comment_id"`
	ReplyUserId    uint64 `json:"reply_user_id"`
	CommentText    string `json:"comment_text"`
	Status         uint64 `json:"status"`
}

type AddCommentResponse struct {
	CommentId      uint64 `json:"comment_id"`
	RelationStatus int64  `json:"relation_status"`
}

type AddPodcastRequest struct {
	Name        string                  `json:"name"`
	Url         string                  `json:"url"`
	Description string                  `json:"description"`
	Cover       string                  `json:"cover"`
	Author      string                  `json:"author"`
	PublishedAt int64                   `json:"published_at"`
	Channel     string                  `json:"channel"`
	Status      int64                   `json:"status"`
	Tags        []string                `json:"tags"`
	Highlights  []*PodcastHighlightItem `json:"highlights"`
}

type AddPodcastResponse struct {
	PodcastId      uint64 `json:"podcast_id"`
	RelationStatus int64  `json:"relation_status"`
}

type AddVideoRequest struct {
	Name        string   `json:"name"`
	Url         string   `json:"url"`
	Description string   `json:"description"`
	Cover       string   `json:"cover"`
	Author      string   `json:"author"`
	PublishedAt int64    `json:"published_at"`
	Tags        []string `json:"tags"`
}

type AddVideoResponse struct {
	VideoID        uint64 `json:"video_id"`
	RelationStatus int64  `json:"relation_status"`
}

type Article struct {
	ArticleID      uint64   `json:"article_id"`
	Name           string   `json:"name"`
	Tags           []string `json:"tags"`
	Url            string   `json:"url"`
	Description    string   `json:"description"`
	Cover          string   `json:"cover"`
	Content        string   `json:"content"`
	Author         string   `json:"author"`
	PublishedAt    int64    `json:"published_at"`
	CreatedAt      int64    `json:"created_at"`
	UpdatedAt      int64    `json:"updated_at"`
	LikeCount      uint64   `json:"like_count"`
	ViewCount      uint64   `json:"view_count"`
	CollectCount   uint64   `json:"collect_count"`
	CommentCount   uint64   `json:"comment_count"`
	LastModifiedBy int64    `json:"last_modified_by"`
	RelationStatus int64    `json:"relation_status"`
	IsLiked        bool     `json:"is_liked"`
	IsCollected    bool     `json:"is_collected"`
}

type CollectRequest struct {
	ContentType string `json:"content_type"`
	ContentId   uint64 `json:"content_id"`
}

type Comic struct {
	ComicID        uint64   `json:"comic_id"`
	Name           string   `json:"name"`
	Tags           []string `json:"tags"`
	Description    string   `json:"description"`
	Cover          string   `json:"cover"`
	Author         string   `json:"author"`
	PublishedAt    int64    `json:"published_at"`
	CreatedAt      int64    `json:"created_at"`
	UpdatedAt      int64    `json:"updated_at"`
	LikeCount      uint64   `json:"like_count"`
	ViewCount      uint64   `json:"view_count"`
	CollectCount   uint64   `json:"collect_count"`
	CommentCount   uint64   `json:"comment_count"`
	ChapterCount   uint64   `json:"chapter_count"`
	LastModifiedBy int64    `json:"last_modified_by"`
	RelationStatus int64    `json:"relation_status"`
	IsLiked        bool     `json:"is_liked"`
	IsCollected    bool     `json:"is_collected"`
}

type ComicChapter struct {
	ComicChapterID uint64 `json:"comic_chapter_id"`
	ComicID        uint64 `json:"comic_id"`
	ChapterNo      int64  `json:"chapter_no"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	Status         int64  `json:"status"`
	PageCount      uint64 `json:"page_count"`
	PublishedAt    int64  `json:"published_at"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type ComicChapterPage struct {
	ComicChapterPageID uint64 `json:"comic_chapter_page_id"`
	ComicChapterID     uint64 `json:"comic_chapter_id"`
	PageNo             int64  `json:"page_no"`
	PageURL            string `json:"page_url"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
}

type Comment struct {
	CommentID      uint64 `json:"comment_id"`
	ContentType    string `json:"content_type"`
	ContentID      uint64 `json:"content_id"`
	UserID         uint64 `json:"user_id"`
	Nickname       string `json:"nickname"`
	Avatar         string `json:"avatar"`
	IpLocation     string `json:"ip_location"`
	ParentID       uint64 `json:"parent_id"`
	ReplyCommentID uint64 `json:"reply_comment_id"`
	ReplyUserID    uint64 `json:"reply_user_id"`
	CommentText    string `json:"comment_text"`
	LikeCount      uint64 `json:"like_count"`
	Status         uint64 `json:"status"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
	IsLiked        bool   `json:"is_liked"`
}

type DeleteArticleRequest struct {
	ArticleId uint64 `form:"article_id"`
}

type DeleteComicChapterRequest struct {
	ComicChapterId uint64 `form:"comic_chapter_id"`
	ComicId        uint64 `form:"comic_id"`
}

type DeleteComicRequest struct {
	ComicId uint64 `form:"comic_id"`
}

type DeleteCommentRequest struct {
	CommentId uint64 `form:"comment_id"`
}

type DeletePodcastRequest struct {
	PodcastId uint64 `form:"podcast_id"`
}

type DeleteVideoRequest struct {
	VideoID uint64 `form:"video_id"`
}

type EmptyResponse struct {
}

type GenerateClassRequest struct {
	ClassName string `json:"class_name"`
}

type GenerateInviteCodeRequest struct {
	Department string `json:"department"`
	MaxUses    uint64 `json:"max_uses"`
	Remark     string `json:"remark"`
	ExpiresAt  int64  `json:"expires_at"`
	TargetRole string `json:"target_role"`
	ClassId    uint64 `json:"class_id"`
}

type GenerateInviteCodeResponse struct {
	InviteCode InviteCode `json:"invite_code"`
}

type GetAnswerRequest struct {
	Question string `json:"question"`
}

type GetAnswerResponse struct {
	Answer string `json:"answer"`
}

type GetArticleContentRequest struct {
	ArticleId uint64 `form:"article_id"`
}

type GetArticleResponse struct {
	Article Article `json:"article"`
}

type GetComicChapterPageResponse struct {
	Pages []ComicChapterPage `json:"pages"`
}

type GetComicChapterRequest struct {
	ComicId  uint64 `form:"comic_id"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"page_size"`
}

type GetComicChapterResponse struct {
	Chapters []ComicChapter `json:"chapters"`
}

type GetComicPageRequest struct {
	ComicChapterId uint64 `form:"comic_chapter_id"`
	Page           int64  `form:"page"`
	PageSize       int64  `form:"page_size"`
}

type GetComicRequest struct {
	ComicId uint64 `form:"comic_id"`
}

type GetComicResponse struct {
	Comic Comic `json:"comic"`
}

type GetInviteCodeRequest struct {
	PageSize int64  `json:"page_size"`
	Cursor   uint64 `json:"cursor"`
}

type GetInviteCodeResponse struct {
	InviteCodes []InviteCode `json:"invite_codes"`
	HasMore     bool         `json:"has_more"`
	NextCursor  uint64       `json:"next_cursor"`
}

type GetPodcastContentRequest struct {
	PodcastId uint64 `form:"podcast_id"`
}

type GetPodcastResponse struct {
	Podcast Podcast `json:"podcast"`
}

type GetRootCommentRequest struct {
	ContentType string `form:"content_type"`
	ContentId   uint64 `form:"content_id"`
	Page        int64  `form:"page"`
	PageSize    int64  `form:"page_size"`
}

type GetRootCommentResponse struct {
	Comments []Comment `json:"comments"`
}

type GetSubCommentRequest struct {
	ContentType     string `form:"content_type"`
	ContentId       uint64 `form:"content_id"`
	ParentCommentId uint64 `form:"parent_comment_id"`
	Page            int64  `form:"page"`
	PageSize        int64  `form:"page_size"`
}

type GetSubCommentResponse struct {
	Comments []Comment `json:"comments"`
}

type GetUserInfoRequest struct {
	UserID uint64 `form:"user_id"`
}

type GetUserInfoResponse struct {
	UserInfo UserInfo `json:"user_info"`
}

type GetVideoContentRequest struct {
	VideoID uint64 `form:"video_id"`
}

type GetVideoResponse struct {
	Video Video `json:"video"`
}

type InviteCode struct {
	Code       string `json:"code"`
	CreatorID  uint64 `json:"creator_id"`
	Department string `json:"department"`
	MaxUses    uint64 `json:"max_uses"`
	UsedCount  uint64 `json:"used_count"`
	Remark     string `json:"remark"`
	ExpiresAt  int64  `json:"expires_at"`
	TargetRole string `json:"target_role"`
	ClassId    uint64 `json:"class_id"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type LikeRequest struct {
	ContentType string `json:"content_type"`
	ContentId   uint64 `json:"content_id"`
}

type LoginRequest struct {
	Tp        string `json:"type"`
	Email     string `json:"email"`
	Password  string `json:"password,optional"`
	EmailCode string `json:"email_code,optional"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type ModifyArticleRequest struct {
	ArticleId   uint64   `json:"article_id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Content     string   `json:"content"`
	Cover       string   `json:"cover"`
	Url         string   `json:"url"`
	PublishedAt int64    `json:"published_at"`
	Author      string   `json:"author"`
	Tags        []string `json:"tags"`
}

type ModifyArticleResponse struct {
	ArticleId      uint64 `json:"article_id"`
	RelationStatus int64  `json:"relation_status"`
}

type ModifyComicChapterRequest struct {
	ComicChapterId uint64   `json:"comic_chapter_id"`
	ComicId        uint64   `json:"comic_id"`
	ChapterNo      int64    `json:"chapter_no"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	Status         int64    `json:"status"`
	PublishedAt    int64    `json:"published_at"`
	PageUrls       []string `json:"page_urls"`
}

type ModifyComicChapterResponse struct {
	ComicChapterId uint64 `json:"comic_chapter_id"`
	RelationStatus int64  `json:"relation_status"`
}

type ModifyComicRequest struct {
	ComicId     uint64   `json:"comic_id"`
	Name        string   `json:"name"`
	Tags        []string `json:"tags"`
	Description string   `json:"description"`
	Cover       string   `json:"cover"`
	Author      string   `json:"author"`
	PublishedAt int64    `json:"published_at"`
}

type ModifyComicResponse struct {
	ComicId        uint64 `json:"comic_id"`
	RelationStatus int64  `json:"relation_status"`
}

type ModifyPodcastRequest struct {
	PodcastId   uint64                  `json:"podcast_id"`
	Name        string                  `json:"name"`
	Url         string                  `json:"url"`
	Description string                  `json:"description"`
	Cover       string                  `json:"cover"`
	Author      string                  `json:"author"`
	PublishedAt int64                   `json:"published_at"`
	Channel     string                  `json:"channel"`
	Status      int64                   `json:"status"`
	Tags        []string                `json:"tags"`
	Highlights  []*PodcastHighlightItem `json:"highlights"`
}

type ModifyPodcastResponse struct {
	PodcastId      uint64 `json:"podcast_id"`
	RelationStatus int64  `json:"relation_status"`
}

type ModifyUserBaseInfoRequest struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Phone  string `json:"phone"`
	UserID uint64 `json:"user_id"`
}

type ModifyVideoRequest struct {
	VideoID     uint64   `json:"video_id"`
	Name        string   `json:"name"`
	Url         string   `json:"url"`
	Description string   `json:"description"`
	Cover       string   `json:"cover"`
	Author      string   `json:"author"`
	PublishedAt int64    `json:"published_at"`
	Tags        []string `json:"tags"`
}

type ModifyVideoResponse struct {
	VideoID        uint64 `json:"video_id"`
	RelationStatus int64  `json:"relation_status"`
}

type Podcast struct {
	PodcastID      uint64                 `json:"podcast_id"`
	Name           string                 `json:"name"`
	Tags           []string               `json:"tags"`
	Url            string                 `json:"url"`
	Description    string                 `json:"description"`
	Cover          string                 `json:"cover"`
	Author         string                 `json:"author"`
	Channel        string                 `json:"channel"`
	Status         int64                  `json:"status"`
	PublishedAt    int64                  `json:"published_at"`
	CreatedAt      int64                  `json:"created_at"`
	UpdatedAt      int64                  `json:"updated_at"`
	LikeCount      uint64                 `json:"like_count"`
	ViewCount      uint64                 `json:"view_count"`
	CollectCount   uint64                 `json:"collect_count"`
	CommentCount   uint64                 `json:"comment_count"`
	Highlights     []PodcastHighlightItem `json:"highlights"`
	LastModifiedBy int64                  `json:"last_modified_by"`
	RelationStatus int64                  `json:"relation_status"`
	IsLiked        bool                   `json:"is_liked"`
	IsCollected    bool                   `json:"is_collected"`
}

type PodcastHighlightItem struct {
	Second    uint64 `json:"second"`
	Highlight string `json:"highlight"`
}

type RegisterRequest struct {
	Email          string `json:"email"`
	EmailCode      string `json:"email_code"`
	Password       string `json:"password"`
	InviteCodeUsed string `json:"invite_code_used"`
}

type RegisterResponse struct {
	User User `json:"user"`
}

type Response struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SendEmailRequest struct {
	Email string `json:"email"`
}

type UnCollectRequest struct {
	ContentType string `json:"content_type"`
	ContentId   uint64 `json:"content_id"`
}

type UnlikeRequest struct {
	ContentType string `json:"content_type"`
	ContentId   uint64 `json:"content_id"`
}

type User struct {
	UserID         uint64 `json:"user_id"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	Avatar         string `json:"avatar"`
	Phone          string `json:"phone"`
	Department     string `json:"department"`
	Role           string `json:"role"`
	ClassID        uint64 `json:"class_id"`
	Status         int64  `json:"status"`
	InviteCodeUsed string `json:"invite_code_used"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type UserInfo struct {
	UserID     uint64 `json:"user_id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"`
	Phone      string `json:"phone"`
	Department string `json:"department"`
	Role       string `json:"role"`
	ClassID    uint64 `json:"class_id"`
	Status     int64  `json:"status"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type ValidateEmailRequest struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type Video struct {
	VideoID        uint64   `json:"video_id"`
	Name           string   `json:"name"`
	Tags           []string `json:"tags"`
	Url            string   `json:"url"`
	Description    string   `json:"description"`
	Cover          string   `json:"cover"`
	Author         string   `json:"author"`
	PublishedAt    int64    `json:"published_at"`
	CreatedAt      int64    `json:"created_at"`
	UpdatedAt      int64    `json:"updated_at"`
	LikeCount      uint64   `json:"like_count"`
	ViewCount      uint64   `json:"view_count"`
	CollectCount   uint64   `json:"collect_count"`
	CommentCount   uint64   `json:"comment_count"`
	LastModifiedBy int64    `json:"last_modified_by"`
	RelationStatus int64    `json:"relation_status"`
	IsLiked        bool     `json:"is_liked"`
	IsCollected    bool     `json:"is_collected"`
}
