// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type GetAnswerRequest struct {
	Question string `json:"question"`
}

type GetAnswerResponse struct {
	Answer string `json:"answer"`
}

type Response struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SendEmailRequest struct {
	Email string `json:"email"`
}

type UploadContentRequest struct {
	File string `form:"file,optional"`
}

type UploadContentResponse struct {
	Url string `json:"url"`
}

type ValidateEmailRequest struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}
