// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Response struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SendEmailRequest struct {
	Email string `json:"email"`
}

type ValidateEmailRequest struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}
