// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: qa.proto

package server

import (
	"context"

	"github.com/luyb177/XiaoAnBackend/qa/internal/logic"
	"github.com/luyb177/XiaoAnBackend/qa/internal/svc"
	"github.com/luyb177/XiaoAnBackend/qa/pb/qa/v1"
)

type QAServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedQAServiceServer
}

func NewQAServiceServer(svcCtx *svc.ServiceContext) *QAServiceServer {
	return &QAServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *QAServiceServer) GetAnswer(ctx context.Context, in *v1.GetAnswerRequest) (*v1.Response, error) {
	l := logic.NewGetAnswerLogic(ctx, s.svcCtx)
	return l.GetAnswer(in)
}
