// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleImageFieldNames          = builder.RawFieldNames(&ArticleImage{})
	articleImageRows                = strings.Join(articleImageFieldNames, ",")
	articleImageRowsExpectAutoSet   = strings.Join(stringx.Remove(articleImageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articleImageRowsWithPlaceHolder = strings.Join(stringx.Remove(articleImageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articleImageModel interface {
		Insert(ctx context.Context, data *ArticleImage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ArticleImage, error)
		Update(ctx context.Context, data *ArticleImage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultArticleImageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ArticleImage struct {
		Id        uint64       `db:"id"`         // 图片ID
		ArticleId uint64       `db:"article_id"` // 文章ID
		Url       string       `db:"url"`        // 图片URL
		Sort      int64        `db:"sort"`       // 图片顺序
		Type      int64        `db:"type"`       // 图片类型: 1内容图 2轮播图
		CreatedAt time.Time    `db:"created_at"`
		DeletedAt sql.NullTime `db:"deleted_at"`
	}
)

func newArticleImageModel(conn sqlx.SqlConn) *defaultArticleImageModel {
	return &defaultArticleImageModel{
		conn:  conn,
		table: "`article_image`",
	}
}

func (m *defaultArticleImageModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleImageModel) FindOne(ctx context.Context, id uint64) (*ArticleImage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleImageRows, m.table)
	var resp ArticleImage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleImageModel) Insert(ctx context.Context, data *ArticleImage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, articleImageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.Url, data.Sort, data.Type, data.DeletedAt)
	return ret, err
}

func (m *defaultArticleImageModel) Update(ctx context.Context, data *ArticleImage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleImageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.Url, data.Sort, data.Type, data.DeletedAt, data.Id)
	return err
}

func (m *defaultArticleImageModel) tableName() string {
	return m.table
}
