// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleTagFieldNames          = builder.RawFieldNames(&ArticleTag{})
	articleTagRows                = strings.Join(articleTagFieldNames, ",")
	articleTagRowsExpectAutoSet   = strings.Join(stringx.Remove(articleTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articleTagRowsWithPlaceHolder = strings.Join(stringx.Remove(articleTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articleTagModel interface {
		Insert(ctx context.Context, data *ArticleTag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ArticleTag, error)
		FindOneByArticleIdTag(ctx context.Context, articleId uint64, tag string) (*ArticleTag, error)
		Update(ctx context.Context, data *ArticleTag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultArticleTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ArticleTag struct {
		Id        uint64 `db:"id"`
		ArticleId uint64 `db:"article_id"` // 文章ID
		Tag       string `db:"tag"`        // 标签
		CreatedAt int64  `db:"created_at"` // 创建时间
	}
)

func newArticleTagModel(conn sqlx.SqlConn) *defaultArticleTagModel {
	return &defaultArticleTagModel{
		conn:  conn,
		table: "`article_tag`",
	}
}

func (m *defaultArticleTagModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultArticleTagModel) FindOne(ctx context.Context, id uint64) (*ArticleTag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleTagRows, m.table)
	var resp ArticleTag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleTagModel) FindOneByArticleIdTag(ctx context.Context, articleId uint64, tag string) (*ArticleTag, error) {
	var resp ArticleTag
	query := fmt.Sprintf("select %s from %s where `article_id` = ? and `tag` = ? limit 1", articleTagRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, articleId, tag)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleTagModel) Insert(ctx context.Context, data *ArticleTag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, articleTagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ArticleId, data.Tag)
	return ret, err
}

func (m *defaultArticleTagModel) Update(ctx context.Context, newData *ArticleTag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleTagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ArticleId, newData.Tag, newData.Id)
	return err
}

func (m *defaultArticleTagModel) tableName() string {
	return m.table
}
