// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	comicUrlFieldNames          = builder.RawFieldNames(&ComicUrl{})
	comicUrlRows                = strings.Join(comicUrlFieldNames, ",")
	comicUrlRowsExpectAutoSet   = strings.Join(stringx.Remove(comicUrlFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	comicUrlRowsWithPlaceHolder = strings.Join(stringx.Remove(comicUrlFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	comicUrlModel interface {
		Insert(ctx context.Context, data *ComicUrl) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ComicUrl, error)
		FindOneByComicIdChapterPage(ctx context.Context, comicId uint64, chapter int64, page int64) (*ComicUrl, error)
		Update(ctx context.Context, data *ComicUrl) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultComicUrlModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ComicUrl struct {
		Id        uint64    `db:"id"`
		ComicId   uint64    `db:"comic_id"`   // 漫画ID
		Chapter   int64     `db:"chapter"`    // 章节（第几话/章）
		Page      int64     `db:"page"`       // 页码（章节内顺序）
		Url       string    `db:"url"`        // 页面资源URL
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newComicUrlModel(conn sqlx.SqlConn) *defaultComicUrlModel {
	return &defaultComicUrlModel{
		conn:  conn,
		table: "`comic_url`",
	}
}

func (m *defaultComicUrlModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultComicUrlModel) FindOne(ctx context.Context, id uint64) (*ComicUrl, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", comicUrlRows, m.table)
	var resp ComicUrl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicUrlModel) FindOneByComicIdChapterPage(ctx context.Context, comicId uint64, chapter int64, page int64) (*ComicUrl, error) {
	var resp ComicUrl
	query := fmt.Sprintf("select %s from %s where `comic_id` = ? and `chapter` = ? and `page` = ? limit 1", comicUrlRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, comicId, chapter, page)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicUrlModel) Insert(ctx context.Context, data *ComicUrl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, comicUrlRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ComicId, data.Chapter, data.Page, data.Url)
	return ret, err
}

func (m *defaultComicUrlModel) Update(ctx context.Context, newData *ComicUrl) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, comicUrlRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ComicId, newData.Chapter, newData.Page, newData.Url, newData.Id)
	return err
}

func (m *defaultComicUrlModel) tableName() string {
	return m.table
}
