// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	comicPageFieldNames          = builder.RawFieldNames(&ComicPage{})
	comicPageRows                = strings.Join(comicPageFieldNames, ",")
	comicPageRowsExpectAutoSet   = strings.Join(stringx.Remove(comicPageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	comicPageRowsWithPlaceHolder = strings.Join(stringx.Remove(comicPageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	comicPageModel interface {
		Insert(ctx context.Context, data *ComicPage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ComicPage, error)
		FindOneByChapterIdPageNoDeletedAt(ctx context.Context, chapterId uint64, pageNo int64, deletedAt uint64) (*ComicPage, error)
		Update(ctx context.Context, data *ComicPage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultComicPageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ComicPage struct {
		Id        uint64    `db:"id"`         // 页面ID
		ChapterId uint64    `db:"chapter_id"` // 章节ID
		PageNo    int64     `db:"page_no"`    // 页码（章节内顺序）
		Url       string    `db:"url"`        // 页面资源URL
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
		DeletedAt uint64    `db:"deleted_at"` // 删除时间戳(0=未删除，>0=删除时间)
	}
)

func newComicPageModel(conn sqlx.SqlConn) *defaultComicPageModel {
	return &defaultComicPageModel{
		conn:  conn,
		table: "`comic_page`",
	}
}

func (m *defaultComicPageModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultComicPageModel) FindOne(ctx context.Context, id uint64) (*ComicPage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", comicPageRows, m.table)
	var resp ComicPage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicPageModel) FindOneByChapterIdPageNoDeletedAt(ctx context.Context, chapterId uint64, pageNo int64, deletedAt uint64) (*ComicPage, error) {
	var resp ComicPage
	query := fmt.Sprintf("select %s from %s where `chapter_id` = ? and `page_no` = ? and `deleted_at` = ? limit 1", comicPageRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, chapterId, pageNo, deletedAt)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicPageModel) Insert(ctx context.Context, data *ComicPage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, comicPageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChapterId, data.PageNo, data.Url, data.DeletedAt)
	return ret, err
}

func (m *defaultComicPageModel) Update(ctx context.Context, newData *ComicPage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, comicPageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ChapterId, newData.PageNo, newData.Url, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultComicPageModel) tableName() string {
	return m.table
}
