// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	comicTagFieldNames          = builder.RawFieldNames(&ComicTag{})
	comicTagRows                = strings.Join(comicTagFieldNames, ",")
	comicTagRowsExpectAutoSet   = strings.Join(stringx.Remove(comicTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	comicTagRowsWithPlaceHolder = strings.Join(stringx.Remove(comicTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	comicTagModel interface {
		Insert(ctx context.Context, data *ComicTag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ComicTag, error)
		FindOneByComicIdTag(ctx context.Context, comicId uint64, tag string) (*ComicTag, error)
		Update(ctx context.Context, data *ComicTag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultComicTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ComicTag struct {
		Id        uint64       `db:"id"`
		ComicId   uint64       `db:"comic_id"`   // 漫画ID
		Tag       string       `db:"tag"`        // 标签
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间(NULL表示未删除)
	}
)

func newComicTagModel(conn sqlx.SqlConn) *defaultComicTagModel {
	return &defaultComicTagModel{
		conn:  conn,
		table: "`comic_tag`",
	}
}

func (m *defaultComicTagModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultComicTagModel) FindOne(ctx context.Context, id uint64) (*ComicTag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", comicTagRows, m.table)
	var resp ComicTag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicTagModel) FindOneByComicIdTag(ctx context.Context, comicId uint64, tag string) (*ComicTag, error) {
	var resp ComicTag
	query := fmt.Sprintf("select %s from %s where `comic_id` = ? and `tag` = ? limit 1", comicTagRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, comicId, tag)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicTagModel) Insert(ctx context.Context, data *ComicTag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, comicTagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ComicId, data.Tag, data.DeletedAt)
	return ret, err
}

func (m *defaultComicTagModel) Update(ctx context.Context, newData *ComicTag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, comicTagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ComicId, newData.Tag, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultComicTagModel) tableName() string {
	return m.table
}
