// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	comicChapterFieldNames          = builder.RawFieldNames(&ComicChapter{})
	comicChapterRows                = strings.Join(comicChapterFieldNames, ",")
	comicChapterRowsExpectAutoSet   = strings.Join(stringx.Remove(comicChapterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	comicChapterRowsWithPlaceHolder = strings.Join(stringx.Remove(comicChapterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	comicChapterModel interface {
		Insert(ctx context.Context, data *ComicChapter) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ComicChapter, error)
		FindOneByComicIdChapterNoDeletedAt(ctx context.Context, comicId uint64, chapterNo int64, deletedAt uint64) (*ComicChapter, error)
		Update(ctx context.Context, data *ComicChapter) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultComicChapterModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ComicChapter struct {
		Id             uint64         `db:"id"`               // 章节ID
		ComicId        uint64         `db:"comic_id"`         // 漫画ID
		ChapterNo      int64          `db:"chapter_no"`       // 章节序号（第几话/章）
		Title          string         `db:"title"`            // 章节标题
		Description    sql.NullString `db:"description"`      // 漫画描述
		PageCount      uint64         `db:"page_count"`       // 页数
		Status         int64          `db:"status"`           // 状态 0-上线 1-下线
		PublishedAt    time.Time      `db:"published_at"`     // 章节发布时间（业务时间）
		RelationStatus int64          `db:"relation_status"`  // 0正常 1待同步
		LastModifiedBy sql.NullInt64  `db:"last_modified_by"` // 最后修改人ID
		CreatedAt      time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time      `db:"updated_at"`       // 更新时间
		DeletedAt      uint64         `db:"deleted_at"`       // 删除时间戳(0=未删除，>0=删除时间)
	}
)

func newComicChapterModel(conn sqlx.SqlConn) *defaultComicChapterModel {
	return &defaultComicChapterModel{
		conn:  conn,
		table: "`comic_chapter`",
	}
}

func (m *defaultComicChapterModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultComicChapterModel) FindOne(ctx context.Context, id uint64) (*ComicChapter, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", comicChapterRows, m.table)
	var resp ComicChapter
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicChapterModel) FindOneByComicIdChapterNoDeletedAt(ctx context.Context, comicId uint64, chapterNo int64, deletedAt uint64) (*ComicChapter, error) {
	var resp ComicChapter
	query := fmt.Sprintf("select %s from %s where `comic_id` = ? and `chapter_no` = ? and `deleted_at` = ? limit 1", comicChapterRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, comicId, chapterNo, deletedAt)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComicChapterModel) Insert(ctx context.Context, data *ComicChapter) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, comicChapterRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ComicId, data.ChapterNo, data.Title, data.Description, data.PageCount, data.Status, data.PublishedAt, data.RelationStatus, data.LastModifiedBy, data.DeletedAt)
	return ret, err
}

func (m *defaultComicChapterModel) Update(ctx context.Context, newData *ComicChapter) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, comicChapterRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ComicId, newData.ChapterNo, newData.Title, newData.Description, newData.PageCount, newData.Status, newData.PublishedAt, newData.RelationStatus, newData.LastModifiedBy, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultComicChapterModel) tableName() string {
	return m.table
}
