// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	contentCollectFieldNames          = builder.RawFieldNames(&ContentCollect{})
	contentCollectRows                = strings.Join(contentCollectFieldNames, ",")
	contentCollectRowsExpectAutoSet   = strings.Join(stringx.Remove(contentCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	contentCollectRowsWithPlaceHolder = strings.Join(stringx.Remove(contentCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	contentCollectModel interface {
		Insert(ctx context.Context, data *ContentCollect) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ContentCollect, error)
		FindOneByUserIdTypeTargetId(ctx context.Context, userId uint64, tp string, targetId uint64) (*ContentCollect, error)
		Update(ctx context.Context, data *ContentCollect) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultContentCollectModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ContentCollect struct {
		Id        uint64       `db:"id"`         // 收藏记录ID
		Type      string       `db:"type"`       // 内容类型: video, comic, podcast, article
		TargetId  uint64       `db:"target_id"`  // 目标内容ID
		UserId    uint64       `db:"user_id"`    // 用户ID
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间(NULL表示未删除)
	}
)

func newContentCollectModel(conn sqlx.SqlConn) *defaultContentCollectModel {
	return &defaultContentCollectModel{
		conn:  conn,
		table: "`content_collect`",
	}
}

func (m *defaultContentCollectModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultContentCollectModel) FindOne(ctx context.Context, id uint64) (*ContentCollect, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", contentCollectRows, m.table)
	var resp ContentCollect
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContentCollectModel) FindOneByUserIdTypeTargetId(ctx context.Context, userId uint64, tp string, targetId uint64) (*ContentCollect, error) {
	var resp ContentCollect
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `type` = ? and `target_id` = ? limit 1", contentCollectRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, tp, targetId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContentCollectModel) Insert(ctx context.Context, data *ContentCollect) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, contentCollectRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Type, data.TargetId, data.UserId, data.DeletedAt)
	return ret, err
}

func (m *defaultContentCollectModel) Update(ctx context.Context, newData *ContentCollect) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, contentCollectRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Type, newData.TargetId, newData.UserId, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultContentCollectModel) tableName() string {
	return m.table
}
