// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	podcastFieldNames          = builder.RawFieldNames(&Podcast{})
	podcastRows                = strings.Join(podcastFieldNames, ",")
	podcastRowsExpectAutoSet   = strings.Join(stringx.Remove(podcastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	podcastRowsWithPlaceHolder = strings.Join(stringx.Remove(podcastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	podcastModel interface {
		Insert(ctx context.Context, data *Podcast) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Podcast, error)
		Update(ctx context.Context, data *Podcast) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPodcastModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Podcast struct {
		Id           uint64         `db:"id"`            // 播客ID
		Name         string         `db:"name"`          // 播客名称
		Url          string         `db:"url"`           // 播客URL
		Description  sql.NullString `db:"description"`   // 播客描述
		Cover        string         `db:"cover"`         // 封面图URL
		Author       string         `db:"author"`        // 作者
		PublishedAt  sql.NullTime   `db:"published_at"`  // 发布时间（业务时间，可修改）
		LikeCount    uint64         `db:"like_count"`    // 点赞数
		ViewCount    uint64         `db:"view_count"`    // 浏览数
		CollectCount uint64         `db:"collect_count"` // 收藏数
		CreatedAt    time.Time      `db:"created_at"`    // 记录创建时间（系统时间）
		UpdatedAt    time.Time      `db:"updated_at"`    // 记录更新时间（系统时间）
		DeletedAt    sql.NullTime   `db:"deleted_at"`    // 软删除时间
	}
)

func newPodcastModel(conn sqlx.SqlConn) *defaultPodcastModel {
	return &defaultPodcastModel{
		conn:  conn,
		table: "`podcast`",
	}
}

func (m *defaultPodcastModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPodcastModel) FindOne(ctx context.Context, id uint64) (*Podcast, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", podcastRows, m.table)
	var resp Podcast
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPodcastModel) Insert(ctx context.Context, data *Podcast) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, podcastRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Url, data.Description, data.Cover, data.Author, data.PublishedAt, data.LikeCount, data.ViewCount, data.CollectCount, data.DeletedAt)
	return ret, err
}

func (m *defaultPodcastModel) Update(ctx context.Context, data *Podcast) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, podcastRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Url, data.Description, data.Cover, data.Author, data.PublishedAt, data.LikeCount, data.ViewCount, data.CollectCount, data.DeletedAt, data.Id)
	return err
}

func (m *defaultPodcastModel) tableName() string {
	return m.table
}
