// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	podcastTagFieldNames          = builder.RawFieldNames(&PodcastTag{})
	podcastTagRows                = strings.Join(podcastTagFieldNames, ",")
	podcastTagRowsExpectAutoSet   = strings.Join(stringx.Remove(podcastTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	podcastTagRowsWithPlaceHolder = strings.Join(stringx.Remove(podcastTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	podcastTagModel interface {
		Insert(ctx context.Context, data *PodcastTag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PodcastTag, error)
		FindOneByPodcastIdTag(ctx context.Context, podcastId uint64, tag string) (*PodcastTag, error)
		Update(ctx context.Context, data *PodcastTag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPodcastTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PodcastTag struct {
		Id        uint64       `db:"id"`
		PodcastId uint64       `db:"podcast_id"` // 播客ID
		Tag       string       `db:"tag"`        // 标签
		CreatedAt time.Time    `db:"created_at"` // 记录创建时间（系统时间）
		UpdatedAt time.Time    `db:"updated_at"` // 记录更新时间（系统时间）
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间
	}
)

func newPodcastTagModel(conn sqlx.SqlConn) *defaultPodcastTagModel {
	return &defaultPodcastTagModel{
		conn:  conn,
		table: "`podcast_tag`",
	}
}

func (m *defaultPodcastTagModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPodcastTagModel) FindOne(ctx context.Context, id uint64) (*PodcastTag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", podcastTagRows, m.table)
	var resp PodcastTag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPodcastTagModel) FindOneByPodcastIdTag(ctx context.Context, podcastId uint64, tag string) (*PodcastTag, error) {
	var resp PodcastTag
	query := fmt.Sprintf("select %s from %s where `podcast_id` = ? and `tag` = ? limit 1", podcastTagRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, podcastId, tag)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPodcastTagModel) Insert(ctx context.Context, data *PodcastTag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, podcastTagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PodcastId, data.Tag, data.DeletedAt)
	return ret, err
}

func (m *defaultPodcastTagModel) Update(ctx context.Context, newData *PodcastTag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, podcastTagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PodcastId, newData.Tag, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultPodcastTagModel) tableName() string {
	return m.table
}
