// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videoTagFieldNames          = builder.RawFieldNames(&VideoTag{})
	videoTagRows                = strings.Join(videoTagFieldNames, ",")
	videoTagRowsExpectAutoSet   = strings.Join(stringx.Remove(videoTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	videoTagRowsWithPlaceHolder = strings.Join(stringx.Remove(videoTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	videoTagModel interface {
		Insert(ctx context.Context, data *VideoTag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*VideoTag, error)
		FindOneByVideoIdTag(ctx context.Context, videoId uint64, tag string) (*VideoTag, error)
		Update(ctx context.Context, data *VideoTag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultVideoTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VideoTag struct {
		Id        uint64 `db:"id"`
		VideoId   uint64 `db:"video_id"`   // 视频ID
		Tag       string `db:"tag"`        // 标签
		CreatedAt int64  `db:"created_at"` // 创建时间
	}
)

func newVideoTagModel(conn sqlx.SqlConn) *defaultVideoTagModel {
	return &defaultVideoTagModel{
		conn:  conn,
		table: "`video_tag`",
	}
}

func (m *defaultVideoTagModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVideoTagModel) FindOne(ctx context.Context, id uint64) (*VideoTag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videoTagRows, m.table)
	var resp VideoTag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoTagModel) FindOneByVideoIdTag(ctx context.Context, videoId uint64, tag string) (*VideoTag, error) {
	var resp VideoTag
	query := fmt.Sprintf("select %s from %s where `video_id` = ? and `tag` = ? limit 1", videoTagRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, videoId, tag)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoTagModel) Insert(ctx context.Context, data *VideoTag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, videoTagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.VideoId, data.Tag)
	return ret, err
}

func (m *defaultVideoTagModel) Update(ctx context.Context, newData *VideoTag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, videoTagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.VideoId, newData.Tag, newData.Id)
	return err
}

func (m *defaultVideoTagModel) tableName() string {
	return m.table
}
