// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videoFieldNames          = builder.RawFieldNames(&Video{})
	videoRows                = strings.Join(videoFieldNames, ",")
	videoRowsExpectAutoSet   = strings.Join(stringx.Remove(videoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	videoRowsWithPlaceHolder = strings.Join(stringx.Remove(videoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	videoModel interface {
		Insert(ctx context.Context, data *Video) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Video, error)
		Update(ctx context.Context, data *Video) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultVideoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Video struct {
		Id           uint64         `db:"id"`            // 视频ID
		Name         string         `db:"name"`          // 视频名称
		Url          string         `db:"url"`           // 视频URL
		Description  sql.NullString `db:"description"`   // 视频描述
		Cover        string         `db:"cover"`         // 封面图URL
		Author       string         `db:"author"`        // 作者
		PublishedAt  sql.NullTime   `db:"published_at"`  // 发布时间（业务时间，可修改）
		CreatedAt    time.Time      `db:"created_at"`    // 记录创建时间（系统时间）
		UpdatedAt    time.Time      `db:"updated_at"`    // 记录更新时间（系统时间）
		DeletedAt    sql.NullTime   `db:"deleted_at"`    // 软删除时间
		LikeCount    uint64         `db:"like_count"`    // 点赞数
		ViewCount    uint64         `db:"view_count"`    // 浏览数
		CollectCount uint64         `db:"collect_count"` // 收藏数
	}
)

func newVideoModel(conn sqlx.SqlConn) *defaultVideoModel {
	return &defaultVideoModel{
		conn:  conn,
		table: "`video`",
	}
}

func (m *defaultVideoModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVideoModel) FindOne(ctx context.Context, id uint64) (*Video, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videoRows, m.table)
	var resp Video
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoModel) Insert(ctx context.Context, data *Video) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, videoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Url, data.Description, data.Cover, data.Author, data.PublishedAt, data.DeletedAt, data.LikeCount, data.ViewCount, data.CollectCount)
	return ret, err
}

func (m *defaultVideoModel) Update(ctx context.Context, data *Video) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, videoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Url, data.Description, data.Cover, data.Author, data.PublishedAt, data.DeletedAt, data.LikeCount, data.ViewCount, data.CollectCount, data.Id)
	return err
}

func (m *defaultVideoModel) tableName() string {
	return m.table
}
