// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatSessionFieldNames          = builder.RawFieldNames(&ChatSession{})
	chatSessionRows                = strings.Join(chatSessionFieldNames, ",")
	chatSessionRowsExpectAutoSet   = strings.Join(stringx.Remove(chatSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatSessionRowsWithPlaceHolder = strings.Join(stringx.Remove(chatSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	chatSessionModel interface {
		Insert(ctx context.Context, data *ChatSession) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ChatSession, error)
		FindOneByUserIdEmptySlotDeletedAt(ctx context.Context, userId uint64, emptySlot sql.NullInt64, deletedAt uint64) (*ChatSession, error)
		Update(ctx context.Context, data *ChatSession) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultChatSessionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChatSession struct {
		Id             uint64        `db:"id"`              // 聊天会话ID
		Title          string        `db:"title"`           // 聊天会话标题
		UserId         uint64        `db:"user_id"`         // 用户ID
		EmptySlot      sql.NullInt64 `db:"empty_slot"`      // 空会话唯一占位(1=空会话,NULL=非空)
		MessageCount   uint64        `db:"message_count"`   // 消息数量
		HasMessage     int64         `db:"has_message"`     // 是否有消息 0没有 1有
		SessionStatus  int64         `db:"session_status"`  // 0空 1进行中 2结束
		IsPinned       int64         `db:"is_pinned"`       // 是否置顶 0否 1是
		PinnedAt       sql.NullTime  `db:"pinned_at"`       // 置顶时间
		LastMessageAt  time.Time     `db:"last_message_at"` // 最后消息时间
		RelationStatus int64         `db:"relation_status"` // 0正常 1待同步
		CreatedAt      time.Time     `db:"created_at"`      // 记录创建时间（系统时间）
		UpdatedAt      time.Time     `db:"updated_at"`      // 记录更新时间（系统时间）
		DeletedAt      uint64        `db:"deleted_at"`      // 删除时间戳(0=未删除，>0=删除时间)
	}
)

func newChatSessionModel(conn sqlx.SqlConn) *defaultChatSessionModel {
	return &defaultChatSessionModel{
		conn:  conn,
		table: "`chat_session`",
	}
}

func (m *defaultChatSessionModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChatSessionModel) FindOne(ctx context.Context, id uint64) (*ChatSession, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatSessionRows, m.table)
	var resp ChatSession
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatSessionModel) FindOneByUserIdEmptySlotDeletedAt(ctx context.Context, userId uint64, emptySlot sql.NullInt64, deletedAt uint64) (*ChatSession, error) {
	var resp ChatSession
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `empty_slot` = ? and `deleted_at` = ? limit 1", chatSessionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, emptySlot, deletedAt)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatSessionModel) Insert(ctx context.Context, data *ChatSession) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, chatSessionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.UserId, data.EmptySlot, data.MessageCount, data.HasMessage, data.SessionStatus, data.IsPinned, data.PinnedAt, data.LastMessageAt, data.RelationStatus, data.DeletedAt)
	return ret, err
}

func (m *defaultChatSessionModel) Update(ctx context.Context, newData *ChatSession) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatSessionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Title, newData.UserId, newData.EmptySlot, newData.MessageCount, newData.HasMessage, newData.SessionStatus, newData.IsPinned, newData.PinnedAt, newData.LastMessageAt, newData.RelationStatus, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultChatSessionModel) tableName() string {
	return m.table
}
