// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: qa.proto

package qaservice

import (
	"context"

	"github.com/luyb177/XiaoAnBackend/qa/pb/qa/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAnswerRequest  = v1.GetAnswerRequest
	GetAnswerResponse = v1.GetAnswerResponse
	Response          = v1.Response

	QAService interface {
		GetAnswer(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*Response, error)
	}

	defaultQAService struct {
		cli zrpc.Client
	}
)

func NewQAService(cli zrpc.Client) QAService {
	return &defaultQAService{
		cli: cli,
	}
}

func (m *defaultQAService) GetAnswer(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewQAServiceClient(m.cli.Conn())
	return client.GetAnswer(ctx, in, opts...)
}
