// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: content.proto

package server

import (
	"context"

	"github.com/luyb177/XiaoAnBackend/content/internal/logic"
	"github.com/luyb177/XiaoAnBackend/content/internal/svc"
	"github.com/luyb177/XiaoAnBackend/content/pb/content/v1"
)

type ContentServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedContentServiceServer
}

func NewContentServiceServer(svcCtx *svc.ServiceContext) *ContentServiceServer {
	return &ContentServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传文件
func (s *ContentServiceServer) UploadContentStream(stream v1.ContentService_UploadContentStreamServer) error {
	l := logic.NewUploadContentStreamLogic(stream.Context(), s.svcCtx)
	return l.UploadContentStream(stream)
}

// 获取访问URL
func (s *ContentServiceServer) GetContentURL(ctx context.Context, in *v1.GetContentURLRequest) (*v1.Response, error) {
	l := logic.NewGetContentURLLogic(ctx, s.svcCtx)
	return l.GetContentURL(in)
}

// AddArticle 添加文章
func (s *ContentServiceServer) AddArticle(ctx context.Context, in *v1.AddArticleRequest) (*v1.Response, error) {
	l := logic.NewAddArticleLogic(ctx, s.svcCtx)
	return l.AddArticle(in)
}

// GetArticle 获取文章
func (s *ContentServiceServer) GetArticle(ctx context.Context, in *v1.GetArticleRequest) (*v1.Response, error) {
	l := logic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

// ModifyArticle 修改文章
func (s *ContentServiceServer) ModifyArticle(ctx context.Context, in *v1.ModifyArticleRequest) (*v1.Response, error) {
	l := logic.NewModifyArticleLogic(ctx, s.svcCtx)
	return l.ModifyArticle(in)
}

// 添加视频
func (s *ContentServiceServer) AddVideo(ctx context.Context, in *v1.AddVideoRequest) (*v1.Response, error) {
	l := logic.NewAddVideoLogic(ctx, s.svcCtx)
	return l.AddVideo(in)
}

// 搜索
func (s *ContentServiceServer) Search(ctx context.Context, in *v1.SearchRequest) (*v1.Response, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

// 点赞
func (s *ContentServiceServer) Like(ctx context.Context, in *v1.LikeRequest) (*v1.Response, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

// 收藏
func (s *ContentServiceServer) Collect(ctx context.Context, in *v1.CollectRequest) (*v1.Response, error) {
	l := logic.NewCollectLogic(ctx, s.svcCtx)
	return l.Collect(in)
}

// 添加评论
func (s *ContentServiceServer) AddComment(ctx context.Context, in *v1.AddCommentRequest) (*v1.Response, error) {
	l := logic.NewAddCommentLogic(ctx, s.svcCtx)
	return l.AddComment(in)
}

// 修改评论
func (s *ContentServiceServer) UpdateComment(ctx context.Context, in *v1.UpdateCommentRequest) (*v1.Response, error) {
	l := logic.NewUpdateCommentLogic(ctx, s.svcCtx)
	return l.UpdateComment(in)
}

// 删除评论
func (s *ContentServiceServer) DeleteComment(ctx context.Context, in *v1.DeleteCommentRequest) (*v1.Response, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

// 获取根评论
func (s *ContentServiceServer) GetComments(ctx context.Context, in *v1.GetCommentsRequest) (*v1.Response, error) {
	l := logic.NewGetCommentsLogic(ctx, s.svcCtx)
	return l.GetComments(in)
}
