// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: content.proto

package server

import (
	"context"

	"github.com/luyb177/XiaoAnBackend/content/internal/logic"
	"github.com/luyb177/XiaoAnBackend/content/internal/svc"
	"github.com/luyb177/XiaoAnBackend/content/pb/content/v1"
)

type ContentServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedContentServiceServer
}

func NewContentServiceServer(svcCtx *svc.ServiceContext) *ContentServiceServer {
	return &ContentServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传文件
func (s *ContentServiceServer) UploadContentStream(stream v1.ContentService_UploadContentStreamServer) error {
	l := logic.NewUploadContentStreamLogic(stream.Context(), s.svcCtx)
	return l.UploadContentStream(stream)
}

// 获取访问URL
func (s *ContentServiceServer) GetContentURL(ctx context.Context, in *v1.GetContentURLRequest) (*v1.Response, error) {
	l := logic.NewGetContentURLLogic(ctx, s.svcCtx)
	return l.GetContentURL(in)
}
