// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package server

import (
	"context"

	"github.com/luyb177/XiaoAnBackend/content/internal/logic"
	"github.com/luyb177/XiaoAnBackend/content/internal/svc"
	"github.com/luyb177/XiaoAnBackend/content/pb/content/v1"
)

type ContentServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedContentServiceServer
}

func NewContentServiceServer(svcCtx *svc.ServiceContext) *ContentServiceServer {
	return &ContentServiceServer{
		svcCtx: svcCtx,
	}
}

// AddArticle 添加文章
func (s *ContentServiceServer) AddArticle(ctx context.Context, in *v1.AddArticleRequest) (*v1.Response, error) {
	l := logic.NewAddArticleLogic(ctx, s.svcCtx)
	return l.AddArticle(in)
}

// GetArticle 获取文章
func (s *ContentServiceServer) GetArticle(ctx context.Context, in *v1.GetArticleRequest) (*v1.Response, error) {
	l := logic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

// ModifyArticle 修改文章
func (s *ContentServiceServer) ModifyArticle(ctx context.Context, in *v1.ModifyArticleRequest) (*v1.Response, error) {
	l := logic.NewModifyArticleLogic(ctx, s.svcCtx)
	return l.ModifyArticle(in)
}

// DeleteArticle 删除文章
func (s *ContentServiceServer) DeleteArticle(ctx context.Context, in *v1.DeleteArticleRequest) (*v1.Response, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}

// AddVideo 添加视频
func (s *ContentServiceServer) AddVideo(ctx context.Context, in *v1.AddVideoRequest) (*v1.Response, error) {
	l := logic.NewAddVideoLogic(ctx, s.svcCtx)
	return l.AddVideo(in)
}

// GetVideo 获取视频
func (s *ContentServiceServer) GetVideo(ctx context.Context, in *v1.GetVideoRequest) (*v1.Response, error) {
	l := logic.NewGetVideoLogic(ctx, s.svcCtx)
	return l.GetVideo(in)
}

// ModifyVideo 修改视频
func (s *ContentServiceServer) ModifyVideo(ctx context.Context, in *v1.ModifyVideoRequest) (*v1.Response, error) {
	l := logic.NewModifyVideoLogic(ctx, s.svcCtx)
	return l.ModifyVideo(in)
}

// DeleteVideo 删除视频
func (s *ContentServiceServer) DeleteVideo(ctx context.Context, in *v1.DeleteVideoRequest) (*v1.Response, error) {
	l := logic.NewDeleteVideoLogic(ctx, s.svcCtx)
	return l.DeleteVideo(in)
}

// AddPodcast 添加播客
func (s *ContentServiceServer) AddPodcast(ctx context.Context, in *v1.AddPodcastRequest) (*v1.Response, error) {
	l := logic.NewAddPodcastLogic(ctx, s.svcCtx)
	return l.AddPodcast(in)
}

// GetPodcast 获取播客
func (s *ContentServiceServer) GetPodcast(ctx context.Context, in *v1.GetPodcastRequest) (*v1.Response, error) {
	l := logic.NewGetPodcastLogic(ctx, s.svcCtx)
	return l.GetPodcast(in)
}

// ModifyPodcast 修改播客
func (s *ContentServiceServer) ModifyPodcast(ctx context.Context, in *v1.ModifyPodcastRequest) (*v1.Response, error) {
	l := logic.NewModifyPodcastLogic(ctx, s.svcCtx)
	return l.ModifyPodcast(in)
}

// DeletePodcast 删除播客
func (s *ContentServiceServer) DeletePodcast(ctx context.Context, in *v1.DeletePodcastRequest) (*v1.Response, error) {
	l := logic.NewDeletePodcastLogic(ctx, s.svcCtx)
	return l.DeletePodcast(in)
}

// AddComic 添加漫画
func (s *ContentServiceServer) AddComic(ctx context.Context, in *v1.AddComicRequest) (*v1.Response, error) {
	l := logic.NewAddComicLogic(ctx, s.svcCtx)
	return l.AddComic(in)
}

// AddComicChapter 添加漫画章节
func (s *ContentServiceServer) AddComicChapter(ctx context.Context, in *v1.AddComicChapterRequest) (*v1.Response, error) {
	l := logic.NewAddComicChapterLogic(ctx, s.svcCtx)
	return l.AddComicChapter(in)
}

// GetComic 获取漫画
func (s *ContentServiceServer) GetComic(ctx context.Context, in *v1.GetComicRequest) (*v1.Response, error) {
	l := logic.NewGetComicLogic(ctx, s.svcCtx)
	return l.GetComic(in)
}

// GetComicChapter 获取漫画章节
func (s *ContentServiceServer) GetComicChapter(ctx context.Context, in *v1.GetComicChapterRequest) (*v1.Response, error) {
	l := logic.NewGetComicChapterLogic(ctx, s.svcCtx)
	return l.GetComicChapter(in)
}

// GetComicPage 获取漫画章节页面
func (s *ContentServiceServer) GetComicPage(ctx context.Context, in *v1.GetComicPageRequest) (*v1.Response, error) {
	l := logic.NewGetComicPageLogic(ctx, s.svcCtx)
	return l.GetComicPage(in)
}

// ModifyComic 修改漫画
func (s *ContentServiceServer) ModifyComic(ctx context.Context, in *v1.ModifyComicRequest) (*v1.Response, error) {
	l := logic.NewModifyComicLogic(ctx, s.svcCtx)
	return l.ModifyComic(in)
}

// ModifyComicChapter 修改漫画章节
func (s *ContentServiceServer) ModifyComicChapter(ctx context.Context, in *v1.ModifyComicChapterRequest) (*v1.Response, error) {
	l := logic.NewModifyComicChapterLogic(ctx, s.svcCtx)
	return l.ModifyComicChapter(in)
}

// DeleteComic 删除漫画
func (s *ContentServiceServer) DeleteComic(ctx context.Context, in *v1.DeleteComicRequest) (*v1.Response, error) {
	l := logic.NewDeleteComicLogic(ctx, s.svcCtx)
	return l.DeleteComic(in)
}

// DeleteComicChapter 删除漫画章节
func (s *ContentServiceServer) DeleteComicChapter(ctx context.Context, in *v1.DeleteComicChapterRequest) (*v1.Response, error) {
	l := logic.NewDeleteComicChapterLogic(ctx, s.svcCtx)
	return l.DeleteComicChapter(in)
}

// AddComment 添加评论
func (s *ContentServiceServer) AddComment(ctx context.Context, in *v1.AddCommentRequest) (*v1.Response, error) {
	l := logic.NewAddCommentLogic(ctx, s.svcCtx)
	return l.AddComment(in)
}

// DeleteComment 删除评论
func (s *ContentServiceServer) DeleteComment(ctx context.Context, in *v1.DeleteCommentRequest) (*v1.Response, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

// GetRootComment 获取评论
func (s *ContentServiceServer) GetRootComment(ctx context.Context, in *v1.GetRootCommentRequest) (*v1.Response, error) {
	l := logic.NewGetRootCommentLogic(ctx, s.svcCtx)
	return l.GetRootComment(in)
}

// GetSubComment 获取子评论
func (s *ContentServiceServer) GetSubComment(ctx context.Context, in *v1.GetSubCommentRequest) (*v1.Response, error) {
	l := logic.NewGetSubCommentLogic(ctx, s.svcCtx)
	return l.GetSubComment(in)
}

// Like 点赞
func (s *ContentServiceServer) Like(ctx context.Context, in *v1.LikeRequest) (*v1.Response, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

// Unlike 取消点赞
func (s *ContentServiceServer) Unlike(ctx context.Context, in *v1.UnlikeRequest) (*v1.Response, error) {
	l := logic.NewUnlikeLogic(ctx, s.svcCtx)
	return l.Unlike(in)
}

// Collect 收藏
func (s *ContentServiceServer) Collect(ctx context.Context, in *v1.CollectRequest) (*v1.Response, error) {
	l := logic.NewCollectLogic(ctx, s.svcCtx)
	return l.Collect(in)
}

// UnCollect 取消收藏
func (s *ContentServiceServer) UnCollect(ctx context.Context, in *v1.UnCollectRequest) (*v1.Response, error) {
	l := logic.NewUnCollectLogic(ctx, s.svcCtx)
	return l.UnCollect(in)
}

// GetNewArticles 获取最新文章列表
func (s *ContentServiceServer) GetNewArticles(ctx context.Context, in *v1.GetNewArticlesRequest) (*v1.Response, error) {
	l := logic.NewGetNewArticlesLogic(ctx, s.svcCtx)
	return l.GetNewArticles(in)
}

// GetNewVideos 获取最新视频列表
func (s *ContentServiceServer) GetNewVideos(ctx context.Context, in *v1.GetNewVideosRequest) (*v1.Response, error) {
	l := logic.NewGetNewVideosLogic(ctx, s.svcCtx)
	return l.GetNewVideos(in)
}

// GetNewPodcasts 获取最新播客列表
func (s *ContentServiceServer) GetNewPodcasts(ctx context.Context, in *v1.GetNewPodcastsRequest) (*v1.Response, error) {
	l := logic.NewGetNewPodcastsLogic(ctx, s.svcCtx)
	return l.GetNewPodcasts(in)
}

// GetNewComics 获取最新漫画列表
func (s *ContentServiceServer) GetNewComics(ctx context.Context, in *v1.GetNewComicsRequest) (*v1.Response, error) {
	l := logic.NewGetNewComicsLogic(ctx, s.svcCtx)
	return l.GetNewComics(in)
}

// 搜索
func (s *ContentServiceServer) Search(ctx context.Context, in *v1.SearchRequest) (*v1.Response, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}
