// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	classFieldNames          = builder.RawFieldNames(&Class{})
	classRows                = strings.Join(classFieldNames, ",")
	classRowsExpectAutoSet   = strings.Join(stringx.Remove(classFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	classRowsWithPlaceHolder = strings.Join(stringx.Remove(classFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	classModel interface {
		Insert(ctx context.Context, data *Class) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Class, error)
		Update(ctx context.Context, data *Class) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultClassModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Class struct {
		Id           uint64         `db:"id"`
		Name         string         `db:"name"`          // 班级名称
		Description  sql.NullString `db:"description"`   // 班级描述
		AdminId      uint64         `db:"admin_id"`      // 班级管理员用户ID
		StudentCount uint64         `db:"student_count"` // 班级人数（缓存）
		Status       int64          `db:"status"`        // 1正常 2冻结 3已解散
		CreatedAt    time.Time      `db:"created_at"`
		UpdatedAt    time.Time      `db:"updated_at"`
		DeletedAt    uint64         `db:"deleted_at"`
	}
)

func newClassModel(conn sqlx.SqlConn) *defaultClassModel {
	return &defaultClassModel{
		conn:  conn,
		table: "`class`",
	}
}

func (m *defaultClassModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultClassModel) FindOne(ctx context.Context, id uint64) (*Class, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", classRows, m.table)
	var resp Class
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClassModel) Insert(ctx context.Context, data *Class) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, classRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.AdminId, data.StudentCount, data.Status, data.DeletedAt)
	return ret, err
}

func (m *defaultClassModel) Update(ctx context.Context, data *Class) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, classRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.AdminId, data.StudentCount, data.Status, data.DeletedAt, data.Id)
	return err
}

func (m *defaultClassModel) tableName() string {
	return m.table
}
