// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inviteCodeFieldNames          = builder.RawFieldNames(&InviteCode{})
	inviteCodeRows                = strings.Join(inviteCodeFieldNames, ",")
	inviteCodeRowsExpectAutoSet   = strings.Join(stringx.Remove(inviteCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	inviteCodeRowsWithPlaceHolder = strings.Join(stringx.Remove(inviteCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	inviteCodeModel interface {
		Insert(ctx context.Context, data *InviteCode) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*InviteCode, error)
		FindOneByCodeDeletedAt(ctx context.Context, code string, deletedAt uint64) (*InviteCode, error)
		Update(ctx context.Context, data *InviteCode) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultInviteCodeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InviteCode struct {
		Id         uint64         `db:"id"`
		Code       string         `db:"code"`
		CreatorId  uint64         `db:"creator_id"`
		Department sql.NullString `db:"department"`
		MaxUses    uint64         `db:"max_uses"`
		UsedCount  uint64         `db:"used_count"`
		IsActive   int64          `db:"is_active"`
		Remark     sql.NullString `db:"remark"`
		CreatedAt  time.Time      `db:"created_at"` // 记录创建时间（系统时间）
		UpdatedAt  time.Time      `db:"updated_at"` // 记录更新时间（系统时间）
		DeletedAt  uint64         `db:"deleted_at"` // 删除时间戳(0=未删除，>0=删除时间)
		ClassId    uint64         `db:"class_id"`
		TargetRole string         `db:"target_role"`
		ExpiresAt  sql.NullTime   `db:"expires_at"`
	}
)

func newInviteCodeModel(conn sqlx.SqlConn) *defaultInviteCodeModel {
	return &defaultInviteCodeModel{
		conn:  conn,
		table: "`invite_code`",
	}
}

func (m *defaultInviteCodeModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultInviteCodeModel) FindOne(ctx context.Context, id uint64) (*InviteCode, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", inviteCodeRows, m.table)
	var resp InviteCode
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInviteCodeModel) FindOneByCodeDeletedAt(ctx context.Context, code string, deletedAt uint64) (*InviteCode, error) {
	var resp InviteCode
	query := fmt.Sprintf("select %s from %s where `code` = ? and `deleted_at` = ? limit 1", inviteCodeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code, deletedAt)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInviteCodeModel) Insert(ctx context.Context, data *InviteCode) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, inviteCodeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.CreatorId, data.Department, data.MaxUses, data.UsedCount, data.IsActive, data.Remark, data.DeletedAt, data.ClassId, data.TargetRole, data.ExpiresAt)
	return ret, err
}

func (m *defaultInviteCodeModel) Update(ctx context.Context, newData *InviteCode) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, inviteCodeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.CreatorId, newData.Department, newData.MaxUses, newData.UsedCount, newData.IsActive, newData.Remark, newData.DeletedAt, newData.ClassId, newData.TargetRole, newData.ExpiresAt, newData.Id)
	return err
}

func (m *defaultInviteCodeModel) tableName() string {
	return m.table
}
