// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inviteCodeFieldNames          = builder.RawFieldNames(&InviteCode{})
	inviteCodeRows                = strings.Join(inviteCodeFieldNames, ",")
	inviteCodeRowsExpectAutoSet   = strings.Join(stringx.Remove(inviteCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	inviteCodeRowsWithPlaceHolder = strings.Join(stringx.Remove(inviteCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	inviteCodeModel interface {
		Insert(ctx context.Context, data *InviteCode) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*InviteCode, error)
		FindOneByCode(ctx context.Context, code string) (*InviteCode, error)
		Update(ctx context.Context, data *InviteCode) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultInviteCodeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InviteCode struct {
		Id          uint64         `db:"id"`
		Code        string         `db:"code"`
		CreatorId   int64          `db:"creator_id"`
		CreatorName sql.NullString `db:"creator_name"`
		Department  sql.NullString `db:"department"`
		MaxUses     int64          `db:"max_uses"`
		UsedCount   int64          `db:"used_count"`
		IsActive    int64          `db:"is_active"`
		Remark      sql.NullString `db:"remark"`
		CreatedAt   int64          `db:"created_at"`
		ExpiresAt   sql.NullInt64  `db:"expires_at"`
		TargetRole  string         `db:"target_role"`
		ClassId     int64          `db:"class_id"`
		Type        string         `db:"type"`
	}
)

func newInviteCodeModel(conn sqlx.SqlConn) *defaultInviteCodeModel {
	return &defaultInviteCodeModel{
		conn:  conn,
		table: "`invite_code`",
	}
}

func (m *defaultInviteCodeModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultInviteCodeModel) FindOne(ctx context.Context, id uint64) (*InviteCode, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", inviteCodeRows, m.table)
	var resp InviteCode
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInviteCodeModel) FindOneByCode(ctx context.Context, code string) (*InviteCode, error) {
	var resp InviteCode
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", inviteCodeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInviteCodeModel) Insert(ctx context.Context, data *InviteCode) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, inviteCodeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.CreatorId, data.CreatorName, data.Department, data.MaxUses, data.UsedCount, data.IsActive, data.Remark, data.ExpiresAt, data.TargetRole, data.ClassId, data.Type)
	return ret, err
}

func (m *defaultInviteCodeModel) Update(ctx context.Context, newData *InviteCode) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, inviteCodeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.CreatorId, newData.CreatorName, newData.Department, newData.MaxUses, newData.UsedCount, newData.IsActive, newData.Remark, newData.ExpiresAt, newData.TargetRole, newData.ClassId, newData.Type, newData.Id)
	return err
}

func (m *defaultInviteCodeModel) tableName() string {
	return m.table
}
