// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package contentservice

import (
	"context"

	"github.com/luyb177/XiaoAnBackend/content/pb/content/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleRequest          = v1.AddArticleRequest
	AddArticleResponse         = v1.AddArticleResponse
	AddComicChapterRequest     = v1.AddComicChapterRequest
	AddComicChapterResponse    = v1.AddComicChapterResponse
	AddComicRequest            = v1.AddComicRequest
	AddComicResponse           = v1.AddComicResponse
	AddCommentRequest          = v1.AddCommentRequest
	AddCommentResponse         = v1.AddCommentResponse
	AddPodcastRequest          = v1.AddPodcastRequest
	AddPodcastResponse         = v1.AddPodcastResponse
	AddVideoRequest            = v1.AddVideoRequest
	AddVideoResponse           = v1.AddVideoResponse
	Article                    = v1.Article
	CollectRequest             = v1.CollectRequest
	Comic                      = v1.Comic
	ComicChapter               = v1.ComicChapter
	ComicPage                  = v1.ComicPage
	Comment                    = v1.Comment
	ContentCollect             = v1.ContentCollect
	ContentLike                = v1.ContentLike
	DeleteArticleRequest       = v1.DeleteArticleRequest
	DeleteComicChapterRequest  = v1.DeleteComicChapterRequest
	DeleteComicRequest         = v1.DeleteComicRequest
	DeleteCommentRequest       = v1.DeleteCommentRequest
	DeletePodcastRequest       = v1.DeletePodcastRequest
	DeleteVideoRequest         = v1.DeleteVideoRequest
	GetArticleRequest          = v1.GetArticleRequest
	GetArticleResponse         = v1.GetArticleResponse
	GetComicChapterRequest     = v1.GetComicChapterRequest
	GetComicChapterResponse    = v1.GetComicChapterResponse
	GetComicPageRequest        = v1.GetComicPageRequest
	GetComicPageResponse       = v1.GetComicPageResponse
	GetComicRequest            = v1.GetComicRequest
	GetComicResponse           = v1.GetComicResponse
	GetCommentResponse         = v1.GetCommentResponse
	GetNewArticlesRequest      = v1.GetNewArticlesRequest
	GetNewArticlesResponse     = v1.GetNewArticlesResponse
	GetNewComicsRequest        = v1.GetNewComicsRequest
	GetNewComicsResponse       = v1.GetNewComicsResponse
	GetNewPodcastsRequest      = v1.GetNewPodcastsRequest
	GetNewPodcastsResponse     = v1.GetNewPodcastsResponse
	GetNewVideosRequest        = v1.GetNewVideosRequest
	GetNewVideosResponse       = v1.GetNewVideosResponse
	GetPodcastRequest          = v1.GetPodcastRequest
	GetPodcastResponse         = v1.GetPodcastResponse
	GetRootCommentRequest      = v1.GetRootCommentRequest
	GetSubCommentRequest       = v1.GetSubCommentRequest
	GetSubCommentResponse      = v1.GetSubCommentResponse
	GetVideoRequest            = v1.GetVideoRequest
	GetVideoResponse           = v1.GetVideoResponse
	LikeRequest                = v1.LikeRequest
	ModifyArticleRequest       = v1.ModifyArticleRequest
	ModifyArticleResponse      = v1.ModifyArticleResponse
	ModifyComicChapterRequest  = v1.ModifyComicChapterRequest
	ModifyComicChapterResponse = v1.ModifyComicChapterResponse
	ModifyComicRequest         = v1.ModifyComicRequest
	ModifyComicResponse        = v1.ModifyComicResponse
	ModifyPodcastRequest       = v1.ModifyPodcastRequest
	ModifyPodcastResponse      = v1.ModifyPodcastResponse
	ModifyVideoRequest         = v1.ModifyVideoRequest
	ModifyVideoResponse        = v1.ModifyVideoResponse
	Podcast                    = v1.Podcast
	PodcastHighlight           = v1.PodcastHighlight
	Response                   = v1.Response
	SearchRequest              = v1.SearchRequest
	SearchResponse             = v1.SearchResponse
	UnCollectRequest           = v1.UnCollectRequest
	UnlikeRequest              = v1.UnlikeRequest
	Video                      = v1.Video

	ContentService interface {
		// AddArticle 添加文章
		AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// GetArticle 获取文章
		GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// ModifyArticle 修改文章
		ModifyArticle(ctx context.Context, in *ModifyArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// DeleteArticle 删除文章
		DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// AddVideo 添加视频
		AddVideo(ctx context.Context, in *AddVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// GetVideo 获取视频
		GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// ModifyVideo 修改视频
		ModifyVideo(ctx context.Context, in *ModifyVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// DeleteVideo 删除视频
		DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// AddPodcast 添加播客
		AddPodcast(ctx context.Context, in *AddPodcastRequest, opts ...grpc.CallOption) (*Response, error)
		// GetPodcast 获取播客
		GetPodcast(ctx context.Context, in *GetPodcastRequest, opts ...grpc.CallOption) (*Response, error)
		// ModifyPodcast 修改播客
		ModifyPodcast(ctx context.Context, in *ModifyPodcastRequest, opts ...grpc.CallOption) (*Response, error)
		// DeletePodcast 删除播客
		DeletePodcast(ctx context.Context, in *DeletePodcastRequest, opts ...grpc.CallOption) (*Response, error)
		// AddComic 添加漫画
		AddComic(ctx context.Context, in *AddComicRequest, opts ...grpc.CallOption) (*Response, error)
		// AddComicChapter 添加漫画章节
		AddComicChapter(ctx context.Context, in *AddComicChapterRequest, opts ...grpc.CallOption) (*Response, error)
		// GetComic 获取漫画
		GetComic(ctx context.Context, in *GetComicRequest, opts ...grpc.CallOption) (*Response, error)
		// GetComicChapter 获取漫画章节
		GetComicChapter(ctx context.Context, in *GetComicChapterRequest, opts ...grpc.CallOption) (*Response, error)
		// GetComicPage 获取漫画章节页面
		GetComicPage(ctx context.Context, in *GetComicPageRequest, opts ...grpc.CallOption) (*Response, error)
		// ModifyComic 修改漫画
		ModifyComic(ctx context.Context, in *ModifyComicRequest, opts ...grpc.CallOption) (*Response, error)
		// ModifyComicChapter 修改漫画章节
		ModifyComicChapter(ctx context.Context, in *ModifyComicChapterRequest, opts ...grpc.CallOption) (*Response, error)
		// DeleteComic 删除漫画
		DeleteComic(ctx context.Context, in *DeleteComicRequest, opts ...grpc.CallOption) (*Response, error)
		// DeleteComicChapter 删除漫画章节
		DeleteComicChapter(ctx context.Context, in *DeleteComicChapterRequest, opts ...grpc.CallOption) (*Response, error)
		// AddComment 添加评论
		AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Response, error)
		// DeleteComment 删除评论
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*Response, error)
		// GetRootComment 获取评论
		GetRootComment(ctx context.Context, in *GetRootCommentRequest, opts ...grpc.CallOption) (*Response, error)
		// GetSubComment 获取子评论
		GetSubComment(ctx context.Context, in *GetSubCommentRequest, opts ...grpc.CallOption) (*Response, error)
		// Like 点赞
		Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*Response, error)
		// Unlike 取消点赞
		Unlike(ctx context.Context, in *UnlikeRequest, opts ...grpc.CallOption) (*Response, error)
		// Collect 收藏
		Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*Response, error)
		// UnCollect 取消收藏
		UnCollect(ctx context.Context, in *UnCollectRequest, opts ...grpc.CallOption) (*Response, error)
		// GetNewArticles 获取最新文章列表
		GetNewArticles(ctx context.Context, in *GetNewArticlesRequest, opts ...grpc.CallOption) (*Response, error)
		// GetNewVideos 获取最新视频列表
		GetNewVideos(ctx context.Context, in *GetNewVideosRequest, opts ...grpc.CallOption) (*Response, error)
		// GetNewPodcasts 获取最新播客列表
		GetNewPodcasts(ctx context.Context, in *GetNewPodcastsRequest, opts ...grpc.CallOption) (*Response, error)
		// GetNewComics 获取最新漫画列表
		GetNewComics(ctx context.Context, in *GetNewComicsRequest, opts ...grpc.CallOption) (*Response, error)
		// 搜索
		Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Response, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

// AddArticle 添加文章
func (m *defaultContentService) AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddArticle(ctx, in, opts...)
}

// GetArticle 获取文章
func (m *defaultContentService) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

// ModifyArticle 修改文章
func (m *defaultContentService) ModifyArticle(ctx context.Context, in *ModifyArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.ModifyArticle(ctx, in, opts...)
}

// DeleteArticle 删除文章
func (m *defaultContentService) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

// AddVideo 添加视频
func (m *defaultContentService) AddVideo(ctx context.Context, in *AddVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddVideo(ctx, in, opts...)
}

// GetVideo 获取视频
func (m *defaultContentService) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetVideo(ctx, in, opts...)
}

// ModifyVideo 修改视频
func (m *defaultContentService) ModifyVideo(ctx context.Context, in *ModifyVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.ModifyVideo(ctx, in, opts...)
}

// DeleteVideo 删除视频
func (m *defaultContentService) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}

// AddPodcast 添加播客
func (m *defaultContentService) AddPodcast(ctx context.Context, in *AddPodcastRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddPodcast(ctx, in, opts...)
}

// GetPodcast 获取播客
func (m *defaultContentService) GetPodcast(ctx context.Context, in *GetPodcastRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetPodcast(ctx, in, opts...)
}

// ModifyPodcast 修改播客
func (m *defaultContentService) ModifyPodcast(ctx context.Context, in *ModifyPodcastRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.ModifyPodcast(ctx, in, opts...)
}

// DeletePodcast 删除播客
func (m *defaultContentService) DeletePodcast(ctx context.Context, in *DeletePodcastRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeletePodcast(ctx, in, opts...)
}

// AddComic 添加漫画
func (m *defaultContentService) AddComic(ctx context.Context, in *AddComicRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddComic(ctx, in, opts...)
}

// AddComicChapter 添加漫画章节
func (m *defaultContentService) AddComicChapter(ctx context.Context, in *AddComicChapterRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddComicChapter(ctx, in, opts...)
}

// GetComic 获取漫画
func (m *defaultContentService) GetComic(ctx context.Context, in *GetComicRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetComic(ctx, in, opts...)
}

// GetComicChapter 获取漫画章节
func (m *defaultContentService) GetComicChapter(ctx context.Context, in *GetComicChapterRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetComicChapter(ctx, in, opts...)
}

// GetComicPage 获取漫画章节页面
func (m *defaultContentService) GetComicPage(ctx context.Context, in *GetComicPageRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetComicPage(ctx, in, opts...)
}

// ModifyComic 修改漫画
func (m *defaultContentService) ModifyComic(ctx context.Context, in *ModifyComicRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.ModifyComic(ctx, in, opts...)
}

// ModifyComicChapter 修改漫画章节
func (m *defaultContentService) ModifyComicChapter(ctx context.Context, in *ModifyComicChapterRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.ModifyComicChapter(ctx, in, opts...)
}

// DeleteComic 删除漫画
func (m *defaultContentService) DeleteComic(ctx context.Context, in *DeleteComicRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteComic(ctx, in, opts...)
}

// DeleteComicChapter 删除漫画章节
func (m *defaultContentService) DeleteComicChapter(ctx context.Context, in *DeleteComicChapterRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteComicChapter(ctx, in, opts...)
}

// AddComment 添加评论
func (m *defaultContentService) AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddComment(ctx, in, opts...)
}

// DeleteComment 删除评论
func (m *defaultContentService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// GetRootComment 获取评论
func (m *defaultContentService) GetRootComment(ctx context.Context, in *GetRootCommentRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetRootComment(ctx, in, opts...)
}

// GetSubComment 获取子评论
func (m *defaultContentService) GetSubComment(ctx context.Context, in *GetSubCommentRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetSubComment(ctx, in, opts...)
}

// Like 点赞
func (m *defaultContentService) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

// Unlike 取消点赞
func (m *defaultContentService) Unlike(ctx context.Context, in *UnlikeRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.Unlike(ctx, in, opts...)
}

// Collect 收藏
func (m *defaultContentService) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.Collect(ctx, in, opts...)
}

// UnCollect 取消收藏
func (m *defaultContentService) UnCollect(ctx context.Context, in *UnCollectRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.UnCollect(ctx, in, opts...)
}

// GetNewArticles 获取最新文章列表
func (m *defaultContentService) GetNewArticles(ctx context.Context, in *GetNewArticlesRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetNewArticles(ctx, in, opts...)
}

// GetNewVideos 获取最新视频列表
func (m *defaultContentService) GetNewVideos(ctx context.Context, in *GetNewVideosRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetNewVideos(ctx, in, opts...)
}

// GetNewPodcasts 获取最新播客列表
func (m *defaultContentService) GetNewPodcasts(ctx context.Context, in *GetNewPodcastsRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetNewPodcasts(ctx, in, opts...)
}

// GetNewComics 获取最新漫画列表
func (m *defaultContentService) GetNewComics(ctx context.Context, in *GetNewComicsRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetNewComics(ctx, in, opts...)
}

// 搜索
func (m *defaultContentService) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.Search(ctx, in, opts...)
}
