// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: content.proto

package contentservice

import (
	"context"

	"github.com/luyb177/XiaoAnBackend/content/pb/content/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddArticleRequest     = v1.AddArticleRequest
	AddArticleResponse    = v1.AddArticleResponse
	AddCommentRequest     = v1.AddCommentRequest
	AddVideoRequest       = v1.AddVideoRequest
	AddVideoResponse      = v1.AddVideoResponse
	Article               = v1.Article
	CollectRequest        = v1.CollectRequest
	Comic                 = v1.Comic
	Comment               = v1.Comment
	CommentDetail         = v1.CommentDetail
	CommentItem           = v1.CommentItem
	ContentCollect        = v1.ContentCollect
	ContentLike           = v1.ContentLike
	DeleteArticleRequest  = v1.DeleteArticleRequest
	DeleteCommentRequest  = v1.DeleteCommentRequest
	DeleteVideoRequest    = v1.DeleteVideoRequest
	GetArticleRequest     = v1.GetArticleRequest
	GetArticleResponse    = v1.GetArticleResponse
	GetCommentsRequest    = v1.GetCommentsRequest
	GetCommentsResponse   = v1.GetCommentsResponse
	GetContentRequest     = v1.GetContentRequest
	GetVideoRequest       = v1.GetVideoRequest
	GetVideoResponse      = v1.GetVideoResponse
	LikeRequest           = v1.LikeRequest
	ModifyArticleRequest  = v1.ModifyArticleRequest
	ModifyArticleResponse = v1.ModifyArticleResponse
	ModifyVideoRequest    = v1.ModifyVideoRequest
	ModifyVideoResponse   = v1.ModifyVideoResponse
	Podcast               = v1.Podcast
	Response              = v1.Response
	SearchRequest         = v1.SearchRequest
	SearchResponse        = v1.SearchResponse
	UpdateCommentRequest  = v1.UpdateCommentRequest
	Video                 = v1.Video

	ContentService interface {
		// AddArticle 添加文章
		AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// GetArticle 获取文章
		GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// ModifyArticle 修改文章
		ModifyArticle(ctx context.Context, in *ModifyArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// DeleteArticle 删除文章
		DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*Response, error)
		// AddVideo 添加视频
		AddVideo(ctx context.Context, in *AddVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// GetVideo 获取视频
		GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// ModifyVideo 修改视频
		ModifyVideo(ctx context.Context, in *ModifyVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// DeleteVideo 删除视频
		DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*Response, error)
		// 搜索
		Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Response, error)
		// 点赞
		Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*Response, error)
		// 收藏
		Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*Response, error)
		// 添加评论
		AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Response, error)
		// 修改评论
		UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Response, error)
		// 删除评论
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*Response, error)
		// 获取根评论
		GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*Response, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

// AddArticle 添加文章
func (m *defaultContentService) AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddArticle(ctx, in, opts...)
}

// GetArticle 获取文章
func (m *defaultContentService) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

// ModifyArticle 修改文章
func (m *defaultContentService) ModifyArticle(ctx context.Context, in *ModifyArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.ModifyArticle(ctx, in, opts...)
}

// DeleteArticle 删除文章
func (m *defaultContentService) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

// AddVideo 添加视频
func (m *defaultContentService) AddVideo(ctx context.Context, in *AddVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddVideo(ctx, in, opts...)
}

// GetVideo 获取视频
func (m *defaultContentService) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetVideo(ctx, in, opts...)
}

// ModifyVideo 修改视频
func (m *defaultContentService) ModifyVideo(ctx context.Context, in *ModifyVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.ModifyVideo(ctx, in, opts...)
}

// DeleteVideo 删除视频
func (m *defaultContentService) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}

// 搜索
func (m *defaultContentService) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.Search(ctx, in, opts...)
}

// 点赞
func (m *defaultContentService) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

// 收藏
func (m *defaultContentService) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.Collect(ctx, in, opts...)
}

// 添加评论
func (m *defaultContentService) AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.AddComment(ctx, in, opts...)
}

// 修改评论
func (m *defaultContentService) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.UpdateComment(ctx, in, opts...)
}

// 删除评论
func (m *defaultContentService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// 获取根评论
func (m *defaultContentService) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewContentServiceClient(m.cli.Conn())
	return client.GetComments(ctx, in, opts...)
}
