// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v4.25.6
// source: pingpong/v1/pingpong.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPingPongEcho = "/api.pingpong.v1.PingPong/Echo"
const OperationPingPongPing = "/api.pingpong.v1.PingPong/Ping"

type PingPongHTTPServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	Ping(context.Context, *PingRequest) (*PongResponse, error)
}

func RegisterPingPongHTTPServer(s *http.Server, srv PingPongHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/ping", _PingPong_Ping0_HTTP_Handler(srv))
	r.POST("/api/v1/echo", _PingPong_Echo0_HTTP_Handler(srv))
}

func _PingPong_Ping0_HTTP_Handler(srv PingPongHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPingPongPing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*PingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PongResponse)
		return ctx.Result(200, reply)
	}
}

func _PingPong_Echo0_HTTP_Handler(srv PingPongHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EchoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPingPongEcho)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Echo(ctx, req.(*EchoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EchoResponse)
		return ctx.Result(200, reply)
	}
}

type PingPongHTTPClient interface {
	Echo(ctx context.Context, req *EchoRequest, opts ...http.CallOption) (rsp *EchoResponse, err error)
	Ping(ctx context.Context, req *PingRequest, opts ...http.CallOption) (rsp *PongResponse, err error)
}

type PingPongHTTPClientImpl struct {
	cc *http.Client
}

func NewPingPongHTTPClient(client *http.Client) PingPongHTTPClient {
	return &PingPongHTTPClientImpl{client}
}

func (c *PingPongHTTPClientImpl) Echo(ctx context.Context, in *EchoRequest, opts ...http.CallOption) (*EchoResponse, error) {
	var out EchoResponse
	pattern := "/api/v1/echo"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPingPongEcho))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PingPongHTTPClientImpl) Ping(ctx context.Context, in *PingRequest, opts ...http.CallOption) (*PongResponse, error) {
	var out PongResponse
	pattern := "/api/v1/ping"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPingPongPing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
